[notebook]
dir = "~/Notes"

[note]
language = "en"
filename = "{{slug title}}"

# MARKDOWN SETTINGS
[format.markdown]
hashtags = true
colon-tags = false 

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]
edit = 'zk edit --interactive --no-input $argv'
list = 'zk list --no-pager --format oneline $argv'
new = 'zk new --title $argv'
ls = 'zk list $argv'
l = 'zk list $argv'
ed = 'zk edit $argv'
e = 'zk edit $argv'
n = 'zk new $argv'
