[notebook]
dir = "~/Notes"

[note]
language = "en"
filename = "{{slug title}}"

# MARKDOWN SETTINGS
[format.markdown]
hashtags = true
colon-tags = false 

# NAMED FILTERS
[filter]
recents = "--sort created- --created-after 'last two weeks'"

# COMMAND ALIASES
[alias]
new = 'zk new --title "$argv"'
edit = 'zk edit --interactive "$argv"'
