# This file has been generated by node2nix 1.11.1. Do not edit!

{nodeEnv, fetchurl, fetchgit, nix-gitignore, stdenv, lib, globalBuildInputs ? []}:

let
  sources = {
    "@astrojs/compiler-2.13.0" = {
      name = "_at_astrojs_slash_compiler";
      packageName = "@astrojs/compiler";
      version = "2.13.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@astrojs/compiler/-/compiler-2.13.0.tgz";
        sha512 = "mqVORhUJViA28fwHYaWmsXSzLO9osbdZ5ImUfxBarqsYdMlPbqAqGJCxsNzvppp1BEzc1mJNjOVvQqeDN8Vspw==";
      };
    };
    "@astrojs/yaml2ts-0.2.2" = {
      name = "_at_astrojs_slash_yaml2ts";
      packageName = "@astrojs/yaml2ts";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/@astrojs/yaml2ts/-/yaml2ts-0.2.2.tgz";
        sha512 = "GOfvSr5Nqy2z5XiwqTouBBpy5FyI6DEe+/g/Mk5am9SjILN1S5fOEvYK0GuWHg98yS/dobP4m8qyqw/URW35fQ==";
      };
    };
    "@emmetio/abbreviation-2.3.3" = {
      name = "_at_emmetio_slash_abbreviation";
      packageName = "@emmetio/abbreviation";
      version = "2.3.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/abbreviation/-/abbreviation-2.3.3.tgz";
        sha512 = "mgv58UrU3rh4YgbE/TzgLQwJ3pFsHHhCLqY20aJq+9comytTXUDNGG/SMtSeMJdkpxgXSXunBGLD8Boka3JyVA==";
      };
    };
    "@emmetio/css-abbreviation-2.1.8" = {
      name = "_at_emmetio_slash_css-abbreviation";
      packageName = "@emmetio/css-abbreviation";
      version = "2.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/css-abbreviation/-/css-abbreviation-2.1.8.tgz";
        sha512 = "s9yjhJ6saOO/uk1V74eifykk2CBYi01STTK3WlXWGOepyKa23ymJ053+DNQjpFcy1ingpaO7AxCcwLvHFY9tuw==";
      };
    };
    "@emmetio/css-parser-0.4.1" = {
      name = "_at_emmetio_slash_css-parser";
      packageName = "@emmetio/css-parser";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/css-parser/-/css-parser-0.4.1.tgz";
        sha512 = "2bC6m0MV/voF4CTZiAbG5MWKbq5EBmDPKu9Sb7s7nVcEzNQlrZP6mFFFlIaISM8X6514H9shWMme1fCm8cWAfQ==";
      };
    };
    "@emmetio/html-matcher-1.3.0" = {
      name = "_at_emmetio_slash_html-matcher";
      packageName = "@emmetio/html-matcher";
      version = "1.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/html-matcher/-/html-matcher-1.3.0.tgz";
        sha512 = "NTbsvppE5eVyBMuyGfVu2CRrLvo7J4YHb6t9sBFLyY03WYhXET37qA4zOYUjBWFCRHO7pS1B9khERtY0f5JXPQ==";
      };
    };
    "@emmetio/scanner-1.0.4" = {
      name = "_at_emmetio_slash_scanner";
      packageName = "@emmetio/scanner";
      version = "1.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/scanner/-/scanner-1.0.4.tgz";
        sha512 = "IqRuJtQff7YHHBk4G8YZ45uB9BaAGcwQeVzgj/zj8/UdOhtQpEIupUhSk8dys6spFIWVZVeK20CzGEnqR5SbqA==";
      };
    };
    "@emmetio/stream-reader-2.2.0" = {
      name = "_at_emmetio_slash_stream-reader";
      packageName = "@emmetio/stream-reader";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/stream-reader/-/stream-reader-2.2.0.tgz";
        sha512 = "fXVXEyFA5Yv3M3n8sUGT7+fvecGrZP4k6FnWWMSZVQf69kAq0LLpaBQLGcPR30m3zMmKYhECP4k/ZkzvhEW5kw==";
      };
    };
    "@emmetio/stream-reader-utils-0.1.0" = {
      name = "_at_emmetio_slash_stream-reader-utils";
      packageName = "@emmetio/stream-reader-utils";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@emmetio/stream-reader-utils/-/stream-reader-utils-0.1.0.tgz";
        sha512 = "ZsZ2I9Vzso3Ho/pjZFsmmZ++FWeEd/txqybHTm4OgaZzdS8V9V/YYWQwg5TC38Z7uLWUV1vavpLLbjJtKubR1A==";
      };
    };
    "@jridgewell/sourcemap-codec-1.5.5" = {
      name = "_at_jridgewell_slash_sourcemap-codec";
      packageName = "@jridgewell/sourcemap-codec";
      version = "1.5.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@jridgewell/sourcemap-codec/-/sourcemap-codec-1.5.5.tgz";
        sha512 = "cYQ9310grqxueWbl+WuIUIaiUaDcj7WOq5fVhEljNVgRfOUhY9fy2zTvfoqWsnebh8Sl70VScFbICvJnLKB0Og==";
      };
    };
    "@mdx-js/language-service-0.7.3" = {
      name = "_at_mdx-js_slash_language-service";
      packageName = "@mdx-js/language-service";
      version = "0.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@mdx-js/language-service/-/language-service-0.7.3.tgz";
        sha512 = "Kspcrl7Z8iFQ9KlA5/NAbMEXPH1ssSzyHsPxslFhDU6Tw8E2SBBSj1Z9Qyj73pvfdwirT7YKWZdeY/QfIWbCiw==";
      };
    };
    "@types/debug-4.1.12" = {
      name = "_at_types_slash_debug";
      packageName = "@types/debug";
      version = "4.1.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/debug/-/debug-4.1.12.tgz";
        sha512 = "vIChWdVG3LG1SMxEvI/AK+FWJthlrqlTu7fbrlywTkkaONwk/UAGaULXRlf8vkzFBLVm0zkMdCquhL5aOjhXPQ==";
      };
    };
    "@types/estree-1.0.8" = {
      name = "_at_types_slash_estree";
      packageName = "@types/estree";
      version = "1.0.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree/-/estree-1.0.8.tgz";
        sha512 = "dWHzHa2WqEXI/O1E9OjrocMTKJl2mSrEolh1Iomrv6U+JuNwaHXsXx9bLu5gG7BUWFIN0skIQJQ/L1rIex4X6w==";
      };
    };
    "@types/estree-jsx-1.0.5" = {
      name = "_at_types_slash_estree-jsx";
      packageName = "@types/estree-jsx";
      version = "1.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/estree-jsx/-/estree-jsx-1.0.5.tgz";
        sha512 = "52CcUVNFyfb1A2ALocQw/Dd1BQFNmSdkuC3BkZ6iqhdMfQz7JWOFRuJFloOzjk+6WijU56m9oKXFAXc7o3Towg==";
      };
    };
    "@types/hast-3.0.4" = {
      name = "_at_types_slash_hast";
      packageName = "@types/hast";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/hast/-/hast-3.0.4.tgz";
        sha512 = "WPs+bbQw5aCj+x6laNGWLH3wviHtoCv/P3+otBhbOhJgG8qtpdAMlTCxLtsTWA7LH1Oh/bFCHsBn0TPS5m30EQ==";
      };
    };
    "@types/mdast-4.0.4" = {
      name = "_at_types_slash_mdast";
      packageName = "@types/mdast";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/mdast/-/mdast-4.0.4.tgz";
        sha512 = "kGaNbPh1k7AFzgpud/gMdvIm5xuECykRR+JnWKQno9TAXVa6WIVCGTPvYGekIDL4uwCZQSYbUxNBSb1aUo79oA==";
      };
    };
    "@types/ms-2.1.0" = {
      name = "_at_types_slash_ms";
      packageName = "@types/ms";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/ms/-/ms-2.1.0.tgz";
        sha512 = "GsCCIZDE/p3i96vtEqx+7dBUGXrc7zeSK3wwPHIaRThS+9OhWIXRqzs4d6k1SVU8g91DrNRWxWUGhp5KXQb2VA==";
      };
    };
    "@types/unist-2.0.11" = {
      name = "_at_types_slash_unist";
      packageName = "@types/unist";
      version = "2.0.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/unist/-/unist-2.0.11.tgz";
        sha512 = "CmBKiL6NNo/OqgmMn95Fk9Whlp2mtvIv+KNpQKN2F4SjvrEesubTRWGYSg+BnWZOnlCaSTU1sMpsBOzgbYhnsA==";
      };
    };
    "@types/unist-3.0.3" = {
      name = "_at_types_slash_unist";
      packageName = "@types/unist";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/@types/unist/-/unist-3.0.3.tgz";
        sha512 = "ko/gIFJRv177XgZsZcBwnqJN5x/Gien8qNOn0D5bQU/zAzVf9Zt3BlcUiLqhV9y4ARk0GbT3tnUiPNgnTXzc/Q==";
      };
    };
    "@volar/kit-2.4.27" = {
      name = "_at_volar_slash_kit";
      packageName = "@volar/kit";
      version = "2.4.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/kit/-/kit-2.4.27.tgz";
        sha512 = "ilZoQDMLzqmSsImJRWx4YiZ4FcvvPrPnFVmL6hSsIWB6Bn3qc7k88J9yP32dagrs5Y8EXIlvvD/mAFaiuEOACQ==";
      };
    };
    "@volar/language-core-2.4.27" = {
      name = "_at_volar_slash_language-core";
      packageName = "@volar/language-core";
      version = "2.4.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-core/-/language-core-2.4.27.tgz";
        sha512 = "DjmjBWZ4tJKxfNC1F6HyYERNHPYS7L7OPFyCrestykNdUZMFYzI9WTyvwPcaNaHlrEUwESHYsfEw3isInncZxQ==";
      };
    };
    "@volar/language-server-2.4.27" = {
      name = "_at_volar_slash_language-server";
      packageName = "@volar/language-server";
      version = "2.4.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-server/-/language-server-2.4.27.tgz";
        sha512 = "SymGNkErcHg8GjiG65iQN8sLkhqu1pwKhFySmxeBuYq5xFYagKBW36eiNITXQTdvT0tutI1GXcXdq/FdE/IyjA==";
      };
    };
    "@volar/language-service-2.4.27" = {
      name = "_at_volar_slash_language-service";
      packageName = "@volar/language-service";
      version = "2.4.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/language-service/-/language-service-2.4.27.tgz";
        sha512 = "SxKZ8yLhpWa7Y5e/RDxtNfm7j7xsXp/uf2urijXEffRNpPSmVdfzQrFFy5d7l8PNpZy+bHg+yakmqBPjQN+MOw==";
      };
    };
    "@volar/source-map-2.4.27" = {
      name = "_at_volar_slash_source-map";
      packageName = "@volar/source-map";
      version = "2.4.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/source-map/-/source-map-2.4.27.tgz";
        sha512 = "ynlcBReMgOZj2i6po+qVswtDUeeBRCTgDurjMGShbm8WYZgJ0PA4RmtebBJ0BCYol1qPv3GQF6jK7C9qoVc7lg==";
      };
    };
    "@volar/typescript-2.4.27" = {
      name = "_at_volar_slash_typescript";
      packageName = "@volar/typescript";
      version = "2.4.27";
      src = fetchurl {
        url = "https://registry.npmjs.org/@volar/typescript/-/typescript-2.4.27.tgz";
        sha512 = "eWaYCcl/uAPInSK2Lze6IqVWaBu/itVqR5InXcHXFyles4zO++Mglt3oxdgj75BDcv1Knr9Y93nowS8U3wqhxg==";
      };
    };
    "@vscode/emmet-helper-2.11.0" = {
      name = "_at_vscode_slash_emmet-helper";
      packageName = "@vscode/emmet-helper";
      version = "2.11.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/emmet-helper/-/emmet-helper-2.11.0.tgz";
        sha512 = "QLxjQR3imPZPQltfbWRnHU6JecWTF1QSWhx3GAKQpslx7y3Dp6sIIXhKjiUJ/BR9FX8PVthjr9PD6pNwOJfAzw==";
      };
    };
    "@vscode/l10n-0.0.10" = {
      name = "_at_vscode_slash_l10n";
      packageName = "@vscode/l10n";
      version = "0.0.10";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/l10n/-/l10n-0.0.10.tgz";
        sha512 = "E1OCmDcDWa0Ya7vtSjp/XfHFGqYJfh+YPC1RkATU71fTac+j1JjCcB3qwSzmlKAighx2WxhLlfhS0RwAN++PFQ==";
      };
    };
    "@vscode/l10n-0.0.18" = {
      name = "_at_vscode_slash_l10n";
      packageName = "@vscode/l10n";
      version = "0.0.18";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vscode/l10n/-/l10n-0.0.18.tgz";
        sha512 = "KYSIHVmslkaCDyw013pphY+d7x1qV8IZupYfeIfzNA+nsaWHbn5uPuQRvdRFsa9zFzGeudPuoGoZ1Op4jrJXIQ==";
      };
    };
    "@vtsls/language-service-0.3.0" = {
      name = "_at_vtsls_slash_language-service";
      packageName = "@vtsls/language-service";
      version = "0.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vtsls/language-service/-/language-service-0.3.0.tgz";
        sha512 = "u2Z5oY64953CvG1SdI6Zimlbnaqj7OT/sj9zcw/gr/f6pl3e0ryh8lsa376MeC9T/SW7q+Aw0YMyUZIIIZOyng==";
      };
    };
    "@vtsls/vscode-fuzzy-0.1.0" = {
      name = "_at_vtsls_slash_vscode-fuzzy";
      packageName = "@vtsls/vscode-fuzzy";
      version = "0.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/@vtsls/vscode-fuzzy/-/vscode-fuzzy-0.1.0.tgz";
        sha512 = "jpJ6pFyi152BZ65j1D7otCf1YA9xaMqXV6nn2MOF8BNx0mkwIp2lTj26xvGk/mvEtiVvsGN3vMiBNXMxcv6bIA==";
      };
    };
    "acorn-8.15.0" = {
      name = "acorn";
      packageName = "acorn";
      version = "8.15.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn/-/acorn-8.15.0.tgz";
        sha512 = "NZyJarBfL7nWwIq+FDL6Zp/yHEhePMNnnJ0y3qfieCrmNvYct8uvtiV41UvlSe6apAfk0fY1FbWx+NwfmpvtTg==";
      };
    };
    "acorn-jsx-5.3.2" = {
      name = "acorn-jsx";
      packageName = "acorn-jsx";
      version = "5.3.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/acorn-jsx/-/acorn-jsx-5.3.2.tgz";
        sha512 = "rq9s+JNhf0IChjtDXxllJ7g41oZk5SlXtp0LHwyA5cejwn7vKmKp4pPri6YEePv2PU65sAsegbXtIinmDFDXgQ==";
      };
    };
    "ajv-8.17.1" = {
      name = "ajv";
      packageName = "ajv";
      version = "8.17.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv/-/ajv-8.17.1.tgz";
        sha512 = "B/gBuNg5SiMTrPkC+A2+cW0RszwxYmn6VYxB/inlBStS5nx6xHIt/ehKRhIMhqusl7a8LjQoZnjCs5vhwxOQ1g==";
      };
    };
    "ajv-draft-04-1.0.0" = {
      name = "ajv-draft-04";
      packageName = "ajv-draft-04";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/ajv-draft-04/-/ajv-draft-04-1.0.0.tgz";
        sha512 = "mv00Te6nmYbRp5DCwclxtt7yV/joXJPGS7nM+97GdxvuttCOfgI3K4U25zboyeX0O+myI8ERluxQe5wljMmVIw==";
      };
    };
    "argparse-2.0.1" = {
      name = "argparse";
      packageName = "argparse";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/argparse/-/argparse-2.0.1.tgz";
        sha512 = "8+9WqebbFzpX9OR+Wa6O29asIogeRMzcGtAINdpMHHyAg10f05aSFVBbcEqGf/PXw1EjAZ+q2/bEBg3DvurK3Q==";
      };
    };
    "bail-2.0.2" = {
      name = "bail";
      packageName = "bail";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/bail/-/bail-2.0.2.tgz";
        sha512 = "0xO6mYd7JB2YesxDKplafRpsiOzPt9V02ddPCLbY1xYGPOX24NTyN50qnUxgCPcSoYMhKpAuBTjQoRZCAkUDRw==";
      };
    };
    "boolbase-1.0.0" = {
      name = "boolbase";
      packageName = "boolbase";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/boolbase/-/boolbase-1.0.0.tgz";
        sha512 = "JZOSA7Mo9sNGB8+UjSgzdLtokWAky1zbztM3WRLCbZ70/3cTANmQmOdR7y2g+J0e2WXywy1yS468tY+IruqEww==";
      };
    };
    "ccount-2.0.1" = {
      name = "ccount";
      packageName = "ccount";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/ccount/-/ccount-2.0.1.tgz";
        sha512 = "eyrF0jiFpY+3drT6383f1qhkbGsLSifNAjA61IUjZjmLCWjItY6LB9ft9YhoDgwfmclB2zhu51Lc7+95b8NRAg==";
      };
    };
    "character-entities-2.0.2" = {
      name = "character-entities";
      packageName = "character-entities";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities/-/character-entities-2.0.2.tgz";
        sha512 = "shx7oQ0Awen/BRIdkjkvz54PnEEI/EjwXDSIZp86/KKdbafHh1Df/RYGBhn4hbe2+uKC9FnT5UCEdyPz3ai9hQ==";
      };
    };
    "character-entities-html4-2.1.0" = {
      name = "character-entities-html4";
      packageName = "character-entities-html4";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities-html4/-/character-entities-html4-2.1.0.tgz";
        sha512 = "1v7fgQRj6hnSwFpq1Eu0ynr/CDEw0rXo2B61qXrLNdHZmPKgb7fqS1a2JwF0rISo9q77jDI8VMEHoApn8qDoZA==";
      };
    };
    "character-entities-legacy-3.0.0" = {
      name = "character-entities-legacy";
      packageName = "character-entities-legacy";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-entities-legacy/-/character-entities-legacy-3.0.0.tgz";
        sha512 = "RpPp0asT/6ufRm//AJVwpViZbGM/MkjQFxJccQRHmISF/22NBtsHqAWmL+/pmkPWoIUJdWyeVleTl1wydHATVQ==";
      };
    };
    "character-reference-invalid-2.0.1" = {
      name = "character-reference-invalid";
      packageName = "character-reference-invalid";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/character-reference-invalid/-/character-reference-invalid-2.0.1.tgz";
        sha512 = "iBZ4F4wRbyORVsu0jPV7gXkOsGYjGHPmAyv+HiHG8gi5PtC9KI2j1+v8/tlibRvjoWX027ypmG/n0HtO5t7unw==";
      };
    };
    "core-js-3.47.0" = {
      name = "core-js";
      packageName = "core-js";
      version = "3.47.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/core-js/-/core-js-3.47.0.tgz";
        sha512 = "c3Q2VVkGAUyupsjRnaNX6u8Dq2vAdzm9iuPj5FW0fRxzlxgq9Q39MDq10IvmQSpLgHQNyQzQmOo6bgGHmH3NNg==";
      };
    };
    "css-select-5.2.2" = {
      name = "css-select";
      packageName = "css-select";
      version = "5.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-select/-/css-select-5.2.2.tgz";
        sha512 = "TizTzUddG/xYLA3NXodFM0fSbNizXjOKhqiQQwvhlspadZokn1KDy0NZFS0wuEubIYAV5/c1/lAr0TaaFXEXzw==";
      };
    };
    "css-what-6.2.2" = {
      name = "css-what";
      packageName = "css-what";
      version = "6.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/css-what/-/css-what-6.2.2.tgz";
        sha512 = "u/O3vwbptzhMs3L1fQE82ZSLHQQfto5gyZzwteVIEyeaY5Fc7R4dapF/BvRoSYFeqfBk4m0V1Vafq5Pjv25wvA==";
      };
    };
    "debug-4.4.3" = {
      name = "debug";
      packageName = "debug";
      version = "4.4.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/debug/-/debug-4.4.3.tgz";
        sha512 = "RGwwWnwQvkVfavKVt22FGLw+xYSdzARwm0ru6DhTVA3umU5hZc28V3kO4stgYryrTlLpuvgI9GiijltAjNbcqA==";
      };
    };
    "decode-named-character-reference-1.2.0" = {
      name = "decode-named-character-reference";
      packageName = "decode-named-character-reference";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/decode-named-character-reference/-/decode-named-character-reference-1.2.0.tgz";
        sha512 = "c6fcElNV6ShtZXmsgNgFFV5tVX2PaV4g+MOAkb8eXHvn6sryJBrZa9r0zV6+dtTyoCKxtDy5tyQ5ZwQuidtd+Q==";
      };
    };
    "dequal-2.0.3" = {
      name = "dequal";
      packageName = "dequal";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/dequal/-/dequal-2.0.3.tgz";
        sha512 = "0je+qPKHEMohvfRTCEo3CrPG6cAzAYgmzKyxRiYSSDkS6eGJdyVJm7WaYA5ECaAD9wLB2T4EEeymA5aFVcYXCA==";
      };
    };
    "devlop-1.1.0" = {
      name = "devlop";
      packageName = "devlop";
      version = "1.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/devlop/-/devlop-1.1.0.tgz";
        sha512 = "RWmIqhcFf1lRYBvNmr7qTNuyCt/7/ns2jbpp1+PalgE/rDQcBT0fioSMUpJ93irlUhC5hrg4cYqe6U+0ImW0rA==";
      };
    };
    "dom-serializer-2.0.0" = {
      name = "dom-serializer";
      packageName = "dom-serializer";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/dom-serializer/-/dom-serializer-2.0.0.tgz";
        sha512 = "wIkAryiqt/nV5EQKqQpo3SToSOV9J0DnbJqwK7Wv/Trc92zIAYZ4FlMu+JPFW1DfGFt81ZTCGgDEabffXeLyJg==";
      };
    };
    "domelementtype-2.3.0" = {
      name = "domelementtype";
      packageName = "domelementtype";
      version = "2.3.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/domelementtype/-/domelementtype-2.3.0.tgz";
        sha512 = "OLETBj6w0OsagBwdXnPdN0cnMfF9opN69co+7ZrbfPGrdpPVNBUj02spi6B1N7wChLQiPn4CSH/zJvXw56gmHw==";
      };
    };
    "domhandler-5.0.3" = {
      name = "domhandler";
      packageName = "domhandler";
      version = "5.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/domhandler/-/domhandler-5.0.3.tgz";
        sha512 = "cgwlv/1iFQiFnU96XXgROh8xTeetsnJiDsTc7TYCLFd9+/WNkIqPTxiM/8pSd8VIrhXGTf1Ny1q1hquVqDJB5w==";
      };
    };
    "domutils-3.2.2" = {
      name = "domutils";
      packageName = "domutils";
      version = "3.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/domutils/-/domutils-3.2.2.tgz";
        sha512 = "6kZKyUajlDuqlHKVX1w7gyslj9MPIXzIFiz/rGu35uC1wMi+kMhQwGhl4lt9unC9Vb9INnY9Z3/ZA3+FhASLaw==";
      };
    };
    "emmet-2.4.11" = {
      name = "emmet";
      packageName = "emmet";
      version = "2.4.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/emmet/-/emmet-2.4.11.tgz";
        sha512 = "23QPJB3moh/U9sT4rQzGgeyyGIrcM+GH5uVYg2C6wZIxAIJq7Ng3QLT79tl8FUwDXhyq9SusfknOrofAKqvgyQ==";
      };
    };
    "entities-4.5.0" = {
      name = "entities";
      packageName = "entities";
      version = "4.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/entities/-/entities-4.5.0.tgz";
        sha512 = "V0hjH4dGPh9Ao5p0MoRY6BVqtwCjhz6vI5LT8AJ55H+4g9/4vbHx1I54fS0XuclLhDHArPQCiMjDxjaL8fPxhw==";
      };
    };
    "escape-string-regexp-5.0.0" = {
      name = "escape-string-regexp";
      packageName = "escape-string-regexp";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/escape-string-regexp/-/escape-string-regexp-5.0.0.tgz";
        sha512 = "/veY75JbMK4j1yjvuUxuVsiS/hr/4iHs9FTT6cgTexxdE0Ly/glccBAkloH/DofkjRbZU3bnoj38mOmhkZ0lHw==";
      };
    };
    "estree-util-is-identifier-name-3.0.0" = {
      name = "estree-util-is-identifier-name";
      packageName = "estree-util-is-identifier-name";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-util-is-identifier-name/-/estree-util-is-identifier-name-3.0.0.tgz";
        sha512 = "hFtqIDZTIUZ9BXLb8y4pYGyk6+wekIivNVTcmvk8NoOh+VeRn5y6cEHzbURrWbfp1fIqdVipilzj+lfaadNZmg==";
      };
    };
    "estree-util-scope-1.0.0" = {
      name = "estree-util-scope";
      packageName = "estree-util-scope";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-util-scope/-/estree-util-scope-1.0.0.tgz";
        sha512 = "2CAASclonf+JFWBNJPndcOpA8EMJwa0Q8LUFJEKqXLW6+qBvbFZuF5gItbQOs/umBUkjviCSDCbBwU2cXbmrhQ==";
      };
    };
    "estree-util-visit-2.0.0" = {
      name = "estree-util-visit";
      packageName = "estree-util-visit";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-util-visit/-/estree-util-visit-2.0.0.tgz";
        sha512 = "m5KgiH85xAhhW8Wta0vShLcUvOsh3LLPI2YVwcbio1l7E09NTLL1EyMZFM1OyWowoH0skScNbhOPl4kcBgzTww==";
      };
    };
    "estree-walker-3.0.3" = {
      name = "estree-walker";
      packageName = "estree-walker";
      version = "3.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/estree-walker/-/estree-walker-3.0.3.tgz";
        sha512 = "7RUKfXgSMMkzt6ZuXmqapOurLGPPfgj6l9uRZ7lRGolvk0y2yocc35LdcxKC5PQZdn2DMqioAQ2NoWcrTKmm6g==";
      };
    };
    "extend-3.0.2" = {
      name = "extend";
      packageName = "extend";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/extend/-/extend-3.0.2.tgz";
        sha512 = "fjquC59cD7CyW6urNXK0FBufkZcoiGG80wTuPujX590cB5Ttln20E2UB4S/WARVqhXffZl2LNgS+gQdPIIim/g==";
      };
    };
    "fast-deep-equal-3.1.3" = {
      name = "fast-deep-equal";
      packageName = "fast-deep-equal";
      version = "3.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-deep-equal/-/fast-deep-equal-3.1.3.tgz";
        sha512 = "f3qQ9oQy9j2AhBe/H9VC91wLmKBCCU/gDOnKNAYG5hswO7BLKj09Hc5HYNz9cGI++xlpDCIgDaitVs03ATR84Q==";
      };
    };
    "fast-uri-3.1.0" = {
      name = "fast-uri";
      packageName = "fast-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fast-uri/-/fast-uri-3.1.0.tgz";
        sha512 = "iPeeDKJSWf4IEOasVVrknXpaBV0IApz/gp7S2bb7Z4Lljbl2MGJRqInZiUrQwV16cpzw/D3S5j5Julj/gT52AA==";
      };
    };
    "fault-2.0.1" = {
      name = "fault";
      packageName = "fault";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/fault/-/fault-2.0.1.tgz";
        sha512 = "WtySTkS4OKev5JtpHXnib4Gxiurzh5NCGvWrFaZ34m6JehfTUhKZvn9njTfw48t6JumVQOmrKqpmGcdwxnhqBQ==";
      };
    };
    "fdir-6.5.0" = {
      name = "fdir";
      packageName = "fdir";
      version = "6.5.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/fdir/-/fdir-6.5.0.tgz";
        sha512 = "tIbYtZbucOs0BRGqPJkshJUYdL+SDH7dVM8gjy+ERp3WAUjLEFJE+02kanyHtwjWOnwrKYBiwAmM0p4kLJAnXg==";
      };
    };
    "format-0.2.2" = {
      name = "format";
      packageName = "format";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/format/-/format-0.2.2.tgz";
        sha512 = "wzsgA6WOq+09wrU1tsJ09udeR/YZRaeArL9e1wPbFg3GG2yDnC2ldKpxs4xunpFF9DgqCqOIra3bc1HWrJ37Ww==";
      };
    };
    "he-1.2.0" = {
      name = "he";
      packageName = "he";
      version = "1.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/he/-/he-1.2.0.tgz";
        sha512 = "F/1DnUGPopORZi0ni+CvrCgHQ5FyEAHRLSApuYWMmrbSwoN2Mn/7k+Gl38gJnR7yyDZk6WLXwiGod1JOWNDKGw==";
      };
    };
    "is-alphabetical-2.0.1" = {
      name = "is-alphabetical";
      packageName = "is-alphabetical";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-alphabetical/-/is-alphabetical-2.0.1.tgz";
        sha512 = "FWyyY60MeTNyeSRpkM2Iry0G9hpr7/9kD40mD/cGQEuilcZYS4okz8SN2Q6rLCJ8gbCt6fN+rC+6tMGS99LaxQ==";
      };
    };
    "is-alphanumerical-2.0.1" = {
      name = "is-alphanumerical";
      packageName = "is-alphanumerical";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-alphanumerical/-/is-alphanumerical-2.0.1.tgz";
        sha512 = "hmbYhX/9MUMF5uh7tOXyK/n0ZvWpad5caBA17GsC6vyuCqaWliRG5K1qS9inmUhEMaOBIW7/whAnSwveW/LtZw==";
      };
    };
    "is-decimal-2.0.1" = {
      name = "is-decimal";
      packageName = "is-decimal";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-decimal/-/is-decimal-2.0.1.tgz";
        sha512 = "AAB9hiomQs5DXWcRB1rqsxGUstbRroFOPPVAomNk/3XHR5JyEZChOyTWe2oayKnsSsr/kcGqF+z6yuH6HHpN0A==";
      };
    };
    "is-hexadecimal-2.0.1" = {
      name = "is-hexadecimal";
      packageName = "is-hexadecimal";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-hexadecimal/-/is-hexadecimal-2.0.1.tgz";
        sha512 = "DgZQp241c8oO6cA1SbTEWiXeoxV42vlcJxgH+B3hi1AiqqKruZR3ZGF8In3fj4+/y/7rHvlOZLZtgJ/4ttYGZg==";
      };
    };
    "is-plain-obj-4.1.0" = {
      name = "is-plain-obj";
      packageName = "is-plain-obj";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/is-plain-obj/-/is-plain-obj-4.1.0.tgz";
        sha512 = "+Pgi+vMuUNkJyExiMBt5IlFoMyKnr5zhJ4Uspz58WOhBF5QoIZkFyNHIbBAtHwzVAgk5RtndVNsDRN61/mmDqg==";
      };
    };
    "json-schema-traverse-1.0.0" = {
      name = "json-schema-traverse";
      packageName = "json-schema-traverse";
      version = "1.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/json-schema-traverse/-/json-schema-traverse-1.0.0.tgz";
        sha512 = "NM8/P9n3XjXhIZn1lLhkFaACTOURQXjWhV4BA/RnOv8xvgqtqpAX9IO4mRQxSx1Rlo4tqzeqb0sOlruaOy3dug==";
      };
    };
    "jsonc-parser-2.3.1" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-2.3.1.tgz";
        sha512 = "H8jvkz1O50L3dMZCsLqiuB2tA7muqbSg1AtGEkN0leAqGjsUzDJir3Zwr02BhqdcITPg3ei3mZ+HjMocAknhhg==";
      };
    };
    "jsonc-parser-3.3.1" = {
      name = "jsonc-parser";
      packageName = "jsonc-parser";
      version = "3.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/jsonc-parser/-/jsonc-parser-3.3.1.tgz";
        sha512 = "HUgH65KyejrUFPvHFPbqOY0rsFip3Bo5wb4ngvdi1EpCYWUQDC5V+Y7mZws+DLkr4M//zQJoanu1SP+87Dv1oQ==";
      };
    };
    "linkify-it-5.0.0" = {
      name = "linkify-it";
      packageName = "linkify-it";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/linkify-it/-/linkify-it-5.0.0.tgz";
        sha512 = "5aHCbzQRADcdP+ATqnDuhhJ/MRIqDkZX5pyjFHRRysS8vZ5AbqGEoFIb6pYHPZ+L/OC2Lc+xT8uHVVR5CAK/wQ==";
      };
    };
    "lodash-4.17.21" = {
      name = "lodash";
      packageName = "lodash";
      version = "4.17.21";
      src = fetchurl {
        url = "https://registry.npmjs.org/lodash/-/lodash-4.17.21.tgz";
        sha512 = "v2kDEe57lecTulaDIuNTPy3Ry4gLGJ6Z1O3vE1krgXZNrsQ+LFTGHVxVjcXPs17LhbZVGedAJv8XZ1tvj5FvSg==";
      };
    };
    "longest-streak-3.1.0" = {
      name = "longest-streak";
      packageName = "longest-streak";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/longest-streak/-/longest-streak-3.1.0.tgz";
        sha512 = "9Ri+o0JYgehTaVBBDoMqIl8GXtbWg711O3srftcHhZ0dqnETqLaoIK0x17fUw9rFSlK/0NlsKe0Ahhyl5pXE2g==";
      };
    };
    "lru-cache-6.0.0" = {
      name = "lru-cache";
      packageName = "lru-cache";
      version = "6.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/lru-cache/-/lru-cache-6.0.0.tgz";
        sha512 = "Jo6dJ04CmSjuznwJSS3pUeWmd/H0ffTlkXXgwZi+eq1UCmqQwCh+eLsYOYCwY991i2Fah4h1BEMCx4qThGbsiA==";
      };
    };
    "markdown-it-14.1.0" = {
      name = "markdown-it";
      packageName = "markdown-it";
      version = "14.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-it/-/markdown-it-14.1.0.tgz";
        sha512 = "a54IwgWPaeBCAAsv13YgmALOF1elABB08FxO9i+r4VFk5Vl4pKokRPeX8u5TCgSsPi6ec1otfLjdOpVcgbpshg==";
      };
    };
    "markdown-table-3.0.4" = {
      name = "markdown-table";
      packageName = "markdown-table";
      version = "3.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/markdown-table/-/markdown-table-3.0.4.tgz";
        sha512 = "wiYz4+JrLyb/DqW2hkFJxP7Vd7JuTDm77fvbM8VfEQdmSMqcImWeeRbHwZjBjIFki/VaMK2BhFi7oUUZeM5bqw==";
      };
    };
    "mdast-util-find-and-replace-3.0.2" = {
      name = "mdast-util-find-and-replace";
      packageName = "mdast-util-find-and-replace";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-find-and-replace/-/mdast-util-find-and-replace-3.0.2.tgz";
        sha512 = "Tmd1Vg/m3Xz43afeNxDIhWRtFZgM2VLyaf4vSTYwudTyeuTneoL3qtWMA5jeLyz/O1vDJmmV4QuScFCA2tBPwg==";
      };
    };
    "mdast-util-from-markdown-2.0.2" = {
      name = "mdast-util-from-markdown";
      packageName = "mdast-util-from-markdown";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-from-markdown/-/mdast-util-from-markdown-2.0.2.tgz";
        sha512 = "uZhTV/8NBuw0WHkPTrCqDOl0zVe1BIng5ZtHoDk49ME1qqcjYmmLmOf0gELgcRMxN4w2iuIeVso5/6QymSrgmA==";
      };
    };
    "mdast-util-frontmatter-2.0.1" = {
      name = "mdast-util-frontmatter";
      packageName = "mdast-util-frontmatter";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-frontmatter/-/mdast-util-frontmatter-2.0.1.tgz";
        sha512 = "LRqI9+wdgC25P0URIJY9vwocIzCcksduHQ9OF2joxQoyTNVduwLAFUzjoopuRJbJAReaKrNQKAZKL3uCMugWJA==";
      };
    };
    "mdast-util-gfm-3.1.0" = {
      name = "mdast-util-gfm";
      packageName = "mdast-util-gfm";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-gfm/-/mdast-util-gfm-3.1.0.tgz";
        sha512 = "0ulfdQOM3ysHhCJ1p06l0b0VKlhU0wuQs3thxZQagjcjPrlFRqY215uZGHHJan9GEAXd9MbfPjFJz+qMkVR6zQ==";
      };
    };
    "mdast-util-gfm-autolink-literal-2.0.1" = {
      name = "mdast-util-gfm-autolink-literal";
      packageName = "mdast-util-gfm-autolink-literal";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-gfm-autolink-literal/-/mdast-util-gfm-autolink-literal-2.0.1.tgz";
        sha512 = "5HVP2MKaP6L+G6YaxPNjuL0BPrq9orG3TsrZ9YXbA3vDw/ACI4MEsnoDpn6ZNm7GnZgtAcONJyPhOP8tNJQavQ==";
      };
    };
    "mdast-util-gfm-footnote-2.1.0" = {
      name = "mdast-util-gfm-footnote";
      packageName = "mdast-util-gfm-footnote";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-gfm-footnote/-/mdast-util-gfm-footnote-2.1.0.tgz";
        sha512 = "sqpDWlsHn7Ac9GNZQMeUzPQSMzR6Wv0WKRNvQRg0KqHh02fpTz69Qc1QSseNX29bhz1ROIyNyxExfawVKTm1GQ==";
      };
    };
    "mdast-util-gfm-strikethrough-2.0.0" = {
      name = "mdast-util-gfm-strikethrough";
      packageName = "mdast-util-gfm-strikethrough";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-gfm-strikethrough/-/mdast-util-gfm-strikethrough-2.0.0.tgz";
        sha512 = "mKKb915TF+OC5ptj5bJ7WFRPdYtuHv0yTRxK2tJvi+BDqbkiG7h7u/9SI89nRAYcmap2xHQL9D+QG/6wSrTtXg==";
      };
    };
    "mdast-util-gfm-table-2.0.0" = {
      name = "mdast-util-gfm-table";
      packageName = "mdast-util-gfm-table";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-gfm-table/-/mdast-util-gfm-table-2.0.0.tgz";
        sha512 = "78UEvebzz/rJIxLvE7ZtDd/vIQ0RHv+3Mh5DR96p7cS7HsBhYIICDBCu8csTNWNO6tBWfqXPWekRuj2FNOGOZg==";
      };
    };
    "mdast-util-gfm-task-list-item-2.0.0" = {
      name = "mdast-util-gfm-task-list-item";
      packageName = "mdast-util-gfm-task-list-item";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-gfm-task-list-item/-/mdast-util-gfm-task-list-item-2.0.0.tgz";
        sha512 = "IrtvNvjxC1o06taBAVJznEnkiHxLFTzgonUdy8hzFVeDun0uTjxxrRGVaNFqkU1wJR3RBPEfsxmU6jDWPofrTQ==";
      };
    };
    "mdast-util-mdx-3.0.0" = {
      name = "mdast-util-mdx";
      packageName = "mdast-util-mdx";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-mdx/-/mdast-util-mdx-3.0.0.tgz";
        sha512 = "JfbYLAW7XnYTTbUsmpu0kdBUVe+yKVJZBItEjwyYJiDJuZ9w4eeaqks4HQO+R7objWgS2ymV60GYpI14Ug554w==";
      };
    };
    "mdast-util-mdx-expression-2.0.1" = {
      name = "mdast-util-mdx-expression";
      packageName = "mdast-util-mdx-expression";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-mdx-expression/-/mdast-util-mdx-expression-2.0.1.tgz";
        sha512 = "J6f+9hUp+ldTZqKRSg7Vw5V6MqjATc+3E4gf3CFNcuZNWD8XdyI6zQ8GqH7f8169MM6P7hMBRDVGnn7oHB9kXQ==";
      };
    };
    "mdast-util-mdx-jsx-3.2.0" = {
      name = "mdast-util-mdx-jsx";
      packageName = "mdast-util-mdx-jsx";
      version = "3.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-mdx-jsx/-/mdast-util-mdx-jsx-3.2.0.tgz";
        sha512 = "lj/z8v0r6ZtsN/cGNNtemmmfoLAFZnjMbNyLzBafjzikOM+glrjNHPlf6lQDOTccj9n5b0PPihEBbhneMyGs1Q==";
      };
    };
    "mdast-util-mdxjs-esm-2.0.1" = {
      name = "mdast-util-mdxjs-esm";
      packageName = "mdast-util-mdxjs-esm";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-mdxjs-esm/-/mdast-util-mdxjs-esm-2.0.1.tgz";
        sha512 = "EcmOpxsZ96CvlP03NghtH1EsLtr0n9Tm4lPUJUBccV9RwUOneqSycg19n5HGzCf+10LozMRSObtVr3ee1WoHtg==";
      };
    };
    "mdast-util-phrasing-4.1.0" = {
      name = "mdast-util-phrasing";
      packageName = "mdast-util-phrasing";
      version = "4.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-phrasing/-/mdast-util-phrasing-4.1.0.tgz";
        sha512 = "TqICwyvJJpBwvGAMZjj4J2n0X8QWp21b9l0o7eXyVJ25YNWYbJDVIyD1bZXE6WtV6RmKJVYmQAKWa0zWOABz2w==";
      };
    };
    "mdast-util-to-markdown-2.1.2" = {
      name = "mdast-util-to-markdown";
      packageName = "mdast-util-to-markdown";
      version = "2.1.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-markdown/-/mdast-util-to-markdown-2.1.2.tgz";
        sha512 = "xj68wMTvGXVOKonmog6LwyJKrYXZPvlwabaryTjLh9LuvovB/KAH+kvi8Gjj+7rJjsFi23nkUxRQv1KqSroMqA==";
      };
    };
    "mdast-util-to-string-4.0.0" = {
      name = "mdast-util-to-string";
      packageName = "mdast-util-to-string";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdast-util-to-string/-/mdast-util-to-string-4.0.0.tgz";
        sha512 = "0H44vDimn51F0YwvxSJSm0eCDOJTRlmN0R1yBh4HLj9wiV1Dn0QoXGbvFAWj2hSItVTlCmBF1hqKlIyUBVFLPg==";
      };
    };
    "mdurl-2.0.0" = {
      name = "mdurl";
      packageName = "mdurl";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/mdurl/-/mdurl-2.0.0.tgz";
        sha512 = "Lf+9+2r+Tdp5wXDXC4PcIBjTDtq4UKjCPMQhKIuzpJNW0b96kVqSwW0bT7FhRSfmAiFYgP+SCRvdrDozfh0U5w==";
      };
    };
    "micromark-4.0.2" = {
      name = "micromark";
      packageName = "micromark";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark/-/micromark-4.0.2.tgz";
        sha512 = "zpe98Q6kvavpCr1NPVSCMebCKfD7CA2NqZ+rykeNhONIJBpc1tFKt9hucLGwha3jNTNI8lHpctWJWoimVF4PfA==";
      };
    };
    "micromark-core-commonmark-2.0.3" = {
      name = "micromark-core-commonmark";
      packageName = "micromark-core-commonmark";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-core-commonmark/-/micromark-core-commonmark-2.0.3.tgz";
        sha512 = "RDBrHEMSxVFLg6xvnXmb1Ayr2WzLAWjeSATAoxwKYJV94TeNavgoIdA0a9ytzDSVzBy2YKFK+emCPOEibLeCrg==";
      };
    };
    "micromark-extension-frontmatter-2.0.0" = {
      name = "micromark-extension-frontmatter";
      packageName = "micromark-extension-frontmatter";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-frontmatter/-/micromark-extension-frontmatter-2.0.0.tgz";
        sha512 = "C4AkuM3dA58cgZha7zVnuVxBhDsbttIMiytjgsM2XbHAB2faRVaHRle40558FBN+DJcrLNCoqG5mlrpdU4cRtg==";
      };
    };
    "micromark-extension-gfm-3.0.0" = {
      name = "micromark-extension-gfm";
      packageName = "micromark-extension-gfm";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm/-/micromark-extension-gfm-3.0.0.tgz";
        sha512 = "vsKArQsicm7t0z2GugkCKtZehqUm31oeGBV/KVSorWSy8ZlNAv7ytjFhvaryUiCUJYqs+NoE6AFhpQvBTM6Q4w==";
      };
    };
    "micromark-extension-gfm-autolink-literal-2.1.0" = {
      name = "micromark-extension-gfm-autolink-literal";
      packageName = "micromark-extension-gfm-autolink-literal";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm-autolink-literal/-/micromark-extension-gfm-autolink-literal-2.1.0.tgz";
        sha512 = "oOg7knzhicgQ3t4QCjCWgTmfNhvQbDDnJeVu9v81r7NltNCVmhPy1fJRX27pISafdjL+SVc4d3l48Gb6pbRypw==";
      };
    };
    "micromark-extension-gfm-footnote-2.1.0" = {
      name = "micromark-extension-gfm-footnote";
      packageName = "micromark-extension-gfm-footnote";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm-footnote/-/micromark-extension-gfm-footnote-2.1.0.tgz";
        sha512 = "/yPhxI1ntnDNsiHtzLKYnE3vf9JZ6cAisqVDauhp4CEHxlb4uoOTxOCJ+9s51bIB8U1N1FJ1RXOKTIlD5B/gqw==";
      };
    };
    "micromark-extension-gfm-strikethrough-2.1.0" = {
      name = "micromark-extension-gfm-strikethrough";
      packageName = "micromark-extension-gfm-strikethrough";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm-strikethrough/-/micromark-extension-gfm-strikethrough-2.1.0.tgz";
        sha512 = "ADVjpOOkjz1hhkZLlBiYA9cR2Anf8F4HqZUO6e5eDcPQd0Txw5fxLzzxnEkSkfnD0wziSGiv7sYhk/ktvbf1uw==";
      };
    };
    "micromark-extension-gfm-table-2.1.1" = {
      name = "micromark-extension-gfm-table";
      packageName = "micromark-extension-gfm-table";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm-table/-/micromark-extension-gfm-table-2.1.1.tgz";
        sha512 = "t2OU/dXXioARrC6yWfJ4hqB7rct14e8f7m0cbI5hUmDyyIlwv5vEtooptH8INkbLzOatzKuVbQmAYcbWoyz6Dg==";
      };
    };
    "micromark-extension-gfm-tagfilter-2.0.0" = {
      name = "micromark-extension-gfm-tagfilter";
      packageName = "micromark-extension-gfm-tagfilter";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm-tagfilter/-/micromark-extension-gfm-tagfilter-2.0.0.tgz";
        sha512 = "xHlTOmuCSotIA8TW1mDIM6X2O1SiX5P9IuDtqGonFhEK0qgRI4yeC6vMxEV2dgyr2TiD+2PQ10o+cOhdVAcwfg==";
      };
    };
    "micromark-extension-gfm-task-list-item-2.1.0" = {
      name = "micromark-extension-gfm-task-list-item";
      packageName = "micromark-extension-gfm-task-list-item";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-gfm-task-list-item/-/micromark-extension-gfm-task-list-item-2.1.0.tgz";
        sha512 = "qIBZhqxqI6fjLDYFTBIa4eivDMnP+OZqsNwmQ3xNLE4Cxwc+zfQEfbs6tzAo2Hjq+bh6q5F+Z8/cksrLFYWQQw==";
      };
    };
    "micromark-extension-mdx-expression-3.0.1" = {
      name = "micromark-extension-mdx-expression";
      packageName = "micromark-extension-mdx-expression";
      version = "3.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-mdx-expression/-/micromark-extension-mdx-expression-3.0.1.tgz";
        sha512 = "dD/ADLJ1AeMvSAKBwO22zG22N4ybhe7kFIZ3LsDI0GlsNr2A3KYxb0LdC1u5rj4Nw+CHKY0RVdnHX8vj8ejm4Q==";
      };
    };
    "micromark-extension-mdx-jsx-3.0.2" = {
      name = "micromark-extension-mdx-jsx";
      packageName = "micromark-extension-mdx-jsx";
      version = "3.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-mdx-jsx/-/micromark-extension-mdx-jsx-3.0.2.tgz";
        sha512 = "e5+q1DjMh62LZAJOnDraSSbDMvGJ8x3cbjygy2qFEi7HCeUT4BDKCvMozPozcD6WmOt6sVvYDNBKhFSz3kjOVQ==";
      };
    };
    "micromark-extension-mdx-md-2.0.0" = {
      name = "micromark-extension-mdx-md";
      packageName = "micromark-extension-mdx-md";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-mdx-md/-/micromark-extension-mdx-md-2.0.0.tgz";
        sha512 = "EpAiszsB3blw4Rpba7xTOUptcFeBFi+6PY8VnJ2hhimH+vCQDirWgsMpz7w1XcZE7LVrSAUGb9VJpG9ghlYvYQ==";
      };
    };
    "micromark-extension-mdxjs-3.0.0" = {
      name = "micromark-extension-mdxjs";
      packageName = "micromark-extension-mdxjs";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-mdxjs/-/micromark-extension-mdxjs-3.0.0.tgz";
        sha512 = "A873fJfhnJ2siZyUrJ31l34Uqwy4xIFmvPY1oj+Ean5PHcPBYzEsvqvWGaWcfEIr11O5Dlw3p2y0tZWpKHDejQ==";
      };
    };
    "micromark-extension-mdxjs-esm-3.0.0" = {
      name = "micromark-extension-mdxjs-esm";
      packageName = "micromark-extension-mdxjs-esm";
      version = "3.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-extension-mdxjs-esm/-/micromark-extension-mdxjs-esm-3.0.0.tgz";
        sha512 = "DJFl4ZqkErRpq/dAPyeWp15tGrcrrJho1hKK5uBS70BCtfrIFg81sqcTVu3Ta+KD1Tk5vAtBNElWxtAa+m8K9A==";
      };
    };
    "micromark-factory-destination-2.0.1" = {
      name = "micromark-factory-destination";
      packageName = "micromark-factory-destination";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-destination/-/micromark-factory-destination-2.0.1.tgz";
        sha512 = "Xe6rDdJlkmbFRExpTOmRj9N3MaWmbAgdpSrBQvCFqhezUn4AHqJHbaEnfbVYYiexVSs//tqOdY/DxhjdCiJnIA==";
      };
    };
    "micromark-factory-label-2.0.1" = {
      name = "micromark-factory-label";
      packageName = "micromark-factory-label";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-label/-/micromark-factory-label-2.0.1.tgz";
        sha512 = "VFMekyQExqIW7xIChcXn4ok29YE3rnuyveW3wZQWWqF4Nv9Wk5rgJ99KzPvHjkmPXF93FXIbBp6YdW3t71/7Vg==";
      };
    };
    "micromark-factory-mdx-expression-2.0.3" = {
      name = "micromark-factory-mdx-expression";
      packageName = "micromark-factory-mdx-expression";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-mdx-expression/-/micromark-factory-mdx-expression-2.0.3.tgz";
        sha512 = "kQnEtA3vzucU2BkrIa8/VaSAsP+EJ3CKOvhMuJgOEGg9KDC6OAY6nSnNDVRiVNRqj7Y4SlSzcStaH/5jge8JdQ==";
      };
    };
    "micromark-factory-space-2.0.1" = {
      name = "micromark-factory-space";
      packageName = "micromark-factory-space";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-space/-/micromark-factory-space-2.0.1.tgz";
        sha512 = "zRkxjtBxxLd2Sc0d+fbnEunsTj46SWXgXciZmHq0kDYGnck/ZSGj9/wULTV95uoeYiK5hRXP2mJ98Uo4cq/LQg==";
      };
    };
    "micromark-factory-title-2.0.1" = {
      name = "micromark-factory-title";
      packageName = "micromark-factory-title";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-title/-/micromark-factory-title-2.0.1.tgz";
        sha512 = "5bZ+3CjhAd9eChYTHsjy6TGxpOFSKgKKJPJxr293jTbfry2KDoWkhBb6TcPVB4NmzaPhMs1Frm9AZH7OD4Cjzw==";
      };
    };
    "micromark-factory-whitespace-2.0.1" = {
      name = "micromark-factory-whitespace";
      packageName = "micromark-factory-whitespace";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-factory-whitespace/-/micromark-factory-whitespace-2.0.1.tgz";
        sha512 = "Ob0nuZ3PKt/n0hORHyvoD9uZhr+Za8sFoP+OnMcnWK5lngSzALgQYKMr9RJVOWLqQYuyn6ulqGWSXdwf6F80lQ==";
      };
    };
    "micromark-util-character-2.1.1" = {
      name = "micromark-util-character";
      packageName = "micromark-util-character";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-character/-/micromark-util-character-2.1.1.tgz";
        sha512 = "wv8tdUTJ3thSFFFJKtpYKOYiGP2+v96Hvk4Tu8KpCAsTMs6yi+nVmGh1syvSCsaxz45J6Jbw+9DD6g97+NV67Q==";
      };
    };
    "micromark-util-chunked-2.0.1" = {
      name = "micromark-util-chunked";
      packageName = "micromark-util-chunked";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-chunked/-/micromark-util-chunked-2.0.1.tgz";
        sha512 = "QUNFEOPELfmvv+4xiNg2sRYeS/P84pTW0TCgP5zc9FpXetHY0ab7SxKyAQCNCc1eK0459uoLI1y5oO5Vc1dbhA==";
      };
    };
    "micromark-util-classify-character-2.0.1" = {
      name = "micromark-util-classify-character";
      packageName = "micromark-util-classify-character";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-classify-character/-/micromark-util-classify-character-2.0.1.tgz";
        sha512 = "K0kHzM6afW/MbeWYWLjoHQv1sgg2Q9EccHEDzSkxiP/EaagNzCm7T/WMKZ3rjMbvIpvBiZgwR3dKMygtA4mG1Q==";
      };
    };
    "micromark-util-combine-extensions-2.0.1" = {
      name = "micromark-util-combine-extensions";
      packageName = "micromark-util-combine-extensions";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-combine-extensions/-/micromark-util-combine-extensions-2.0.1.tgz";
        sha512 = "OnAnH8Ujmy59JcyZw8JSbK9cGpdVY44NKgSM7E9Eh7DiLS2E9RNQf0dONaGDzEG9yjEl5hcqeIsj4hfRkLH/Bg==";
      };
    };
    "micromark-util-decode-numeric-character-reference-2.0.2" = {
      name = "micromark-util-decode-numeric-character-reference";
      packageName = "micromark-util-decode-numeric-character-reference";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-decode-numeric-character-reference/-/micromark-util-decode-numeric-character-reference-2.0.2.tgz";
        sha512 = "ccUbYk6CwVdkmCQMyr64dXz42EfHGkPQlBj5p7YVGzq8I7CtjXZJrubAYezf7Rp+bjPseiROqe7G6foFd+lEuw==";
      };
    };
    "micromark-util-decode-string-2.0.1" = {
      name = "micromark-util-decode-string";
      packageName = "micromark-util-decode-string";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-decode-string/-/micromark-util-decode-string-2.0.1.tgz";
        sha512 = "nDV/77Fj6eH1ynwscYTOsbK7rR//Uj0bZXBwJZRfaLEJ1iGBR6kIfNmlNqaqJf649EP0F3NWNdeJi03elllNUQ==";
      };
    };
    "micromark-util-encode-2.0.1" = {
      name = "micromark-util-encode";
      packageName = "micromark-util-encode";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-encode/-/micromark-util-encode-2.0.1.tgz";
        sha512 = "c3cVx2y4KqUnwopcO9b/SCdo2O67LwJJ/UyqGfbigahfegL9myoEFoDYZgkT7f36T0bLrM9hZTAaAyH+PCAXjw==";
      };
    };
    "micromark-util-events-to-acorn-2.0.3" = {
      name = "micromark-util-events-to-acorn";
      packageName = "micromark-util-events-to-acorn";
      version = "2.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-events-to-acorn/-/micromark-util-events-to-acorn-2.0.3.tgz";
        sha512 = "jmsiEIiZ1n7X1Rr5k8wVExBQCg5jy4UXVADItHmNk1zkwEVhBuIUKRu3fqv+hs4nxLISi2DQGlqIOGiFxgbfHg==";
      };
    };
    "micromark-util-html-tag-name-2.0.1" = {
      name = "micromark-util-html-tag-name";
      packageName = "micromark-util-html-tag-name";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-html-tag-name/-/micromark-util-html-tag-name-2.0.1.tgz";
        sha512 = "2cNEiYDhCWKI+Gs9T0Tiysk136SnR13hhO8yW6BGNyhOC4qYFnwF1nKfD3HFAIXA5c45RrIG1ub11GiXeYd1xA==";
      };
    };
    "micromark-util-normalize-identifier-2.0.1" = {
      name = "micromark-util-normalize-identifier";
      packageName = "micromark-util-normalize-identifier";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-normalize-identifier/-/micromark-util-normalize-identifier-2.0.1.tgz";
        sha512 = "sxPqmo70LyARJs0w2UclACPUUEqltCkJ6PhKdMIDuJ3gSf/Q+/GIe3WKl0Ijb/GyH9lOpUkRAO2wp0GVkLvS9Q==";
      };
    };
    "micromark-util-resolve-all-2.0.1" = {
      name = "micromark-util-resolve-all";
      packageName = "micromark-util-resolve-all";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-resolve-all/-/micromark-util-resolve-all-2.0.1.tgz";
        sha512 = "VdQyxFWFT2/FGJgwQnJYbe1jjQoNTS4RjglmSjTUlpUMa95Htx9NHeYW4rGDJzbjvCsl9eLjMQwGeElsqmzcHg==";
      };
    };
    "micromark-util-sanitize-uri-2.0.1" = {
      name = "micromark-util-sanitize-uri";
      packageName = "micromark-util-sanitize-uri";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-sanitize-uri/-/micromark-util-sanitize-uri-2.0.1.tgz";
        sha512 = "9N9IomZ/YuGGZZmQec1MbgxtlgougxTodVwDzzEouPKo3qFWvymFHWcnDi2vzV1ff6kas9ucW+o3yzJK9YB1AQ==";
      };
    };
    "micromark-util-subtokenize-2.1.0" = {
      name = "micromark-util-subtokenize";
      packageName = "micromark-util-subtokenize";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-subtokenize/-/micromark-util-subtokenize-2.1.0.tgz";
        sha512 = "XQLu552iSctvnEcgXw6+Sx75GflAPNED1qx7eBJ+wydBb2KCbRZe+NwvIEEMM83uml1+2WSXpBAcp9IUCgCYWA==";
      };
    };
    "micromark-util-symbol-2.0.1" = {
      name = "micromark-util-symbol";
      packageName = "micromark-util-symbol";
      version = "2.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-symbol/-/micromark-util-symbol-2.0.1.tgz";
        sha512 = "vs5t8Apaud9N28kgCrRUdEed4UJ+wWNvicHLPxCa9ENlYuAY31M0ETy5y1vA33YoNPDFTghEbnh6efaE8h4x0Q==";
      };
    };
    "micromark-util-types-2.0.2" = {
      name = "micromark-util-types";
      packageName = "micromark-util-types";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/micromark-util-types/-/micromark-util-types-2.0.2.tgz";
        sha512 = "Yw0ECSpJoViF1qTU4DC6NwtC4aWGt1EkzaQB8KPPyCRR8z9TWeV0HbEFGTO+ZY1wB22zmxnJqhPyTpOVCpeHTA==";
      };
    };
    "ms-2.1.3" = {
      name = "ms";
      packageName = "ms";
      version = "2.1.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/ms/-/ms-2.1.3.tgz";
        sha512 = "6FlzubTLZG3J2a/NVCAleEhjzq5oxgHyaCU9yYXvcLsvoVaHJq/s5xXI6/XXP6tz7R9xAOtHnSO/tXtF3WRTlA==";
      };
    };
    "muggle-string-0.4.1" = {
      name = "muggle-string";
      packageName = "muggle-string";
      version = "0.4.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/muggle-string/-/muggle-string-0.4.1.tgz";
        sha512 = "VNTrAak/KhO2i8dqqnqnAHOa3cYBwXEZe9h+D5h/1ZqFSTEFHdM65lR7RoIqq3tBBYavsOXV84NoHXZ0AkPyqQ==";
      };
    };
    "node-html-parser-6.1.13" = {
      name = "node-html-parser";
      packageName = "node-html-parser";
      version = "6.1.13";
      src = fetchurl {
        url = "https://registry.npmjs.org/node-html-parser/-/node-html-parser-6.1.13.tgz";
        sha512 = "qIsTMOY4C/dAa5Q5vsobRpOOvPfC4pB61UVW2uSwZNUp0QU/jCekTal1vMmbO0DgdHeLUJpv/ARmDqErVxA3Sg==";
      };
    };
    "nth-check-2.1.1" = {
      name = "nth-check";
      packageName = "nth-check";
      version = "2.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/nth-check/-/nth-check-2.1.1.tgz";
        sha512 = "lqjrjmaOoAnWfMmBPL+XNnynZh2+swxiX3WUE0s4yEHI6m+AwrK2UZOimIRl3X/4QctVqS8AiZjFqyOGrMXb/w==";
      };
    };
    "parse-entities-4.0.2" = {
      name = "parse-entities";
      packageName = "parse-entities";
      version = "4.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/parse-entities/-/parse-entities-4.0.2.tgz";
        sha512 = "GG2AQYWoLgL877gQIKeRPGO1xF9+eG1ujIb5soS5gPvLQ1y2o8FL90w2QWNdf9I361Mpp7726c+lj3U0qK1uGw==";
      };
    };
    "path-browserify-1.0.1" = {
      name = "path-browserify";
      packageName = "path-browserify";
      version = "1.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/path-browserify/-/path-browserify-1.0.1.tgz";
        sha512 = "b7uo2UCUOYZcnF/3ID0lulOJi/bafxa1xPe7ZPsammBSpjSWQkjNxlt635YGS2MiR9GjvuXCtz2emr3jbsz98g==";
      };
    };
    "picomatch-2.3.1" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-2.3.1.tgz";
        sha512 = "JU3teHTNjmE2VCGFzuY8EXzCDVwEqB2a8fsIvwaStHhAWJEeVd1o1QD80CU6+ZdEXXSLbSsuLwJjkCBWqRQUVA==";
      };
    };
    "picomatch-4.0.3" = {
      name = "picomatch";
      packageName = "picomatch";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/picomatch/-/picomatch-4.0.3.tgz";
        sha512 = "5gTmgEY/sqK6gFXLIsQNH19lWb4ebPDLA4SdLP7dsWkIXHWlG66oPuVvXSGFPppYZz8ZDZq0dYYrbHfBCVUb1Q==";
      };
    };
    "prettier-3.8.0" = {
      name = "prettier";
      packageName = "prettier";
      version = "3.8.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier/-/prettier-3.8.0.tgz";
        sha512 = "yEPsovQfpxYfgWNhCfECjG5AQaO+K3dp6XERmOepyPDVqcJm+bjyCVO3pmU+nAPe0N5dDvekfGezt/EIiRe1TA==";
      };
    };
    "prettier-plugin-astro-0.14.1" = {
      name = "prettier-plugin-astro";
      packageName = "prettier-plugin-astro";
      version = "0.14.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/prettier-plugin-astro/-/prettier-plugin-astro-0.14.1.tgz";
        sha512 = "RiBETaaP9veVstE4vUwSIcdATj6dKmXljouXc/DDNwBSPTp8FRkLGDSGFClKsAFeeg+13SB0Z1JZvbD76bigJw==";
      };
    };
    "punycode.js-2.3.1" = {
      name = "punycode.js";
      packageName = "punycode.js";
      version = "2.3.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/punycode.js/-/punycode.js-2.3.1.tgz";
        sha512 = "uxFIHU0YlHYhDQtV4R9J6a52SLx28BCjT+4ieh7IGbgwVJWO+km431c4yRlREUAsAmt/uMjQUyQHNEPf0M39CA==";
      };
    };
    "regenerator-runtime-0.13.11" = {
      name = "regenerator-runtime";
      packageName = "regenerator-runtime";
      version = "0.13.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/regenerator-runtime/-/regenerator-runtime-0.13.11.tgz";
        sha512 = "kY1AZVr2Ra+t+piVaJ4gxaFaReZVH40AKNo7UCX6W+dEwBo/2oZJzqfuN1qLq1oL45o56cPaTXELwrTh8Fpggg==";
      };
    };
    "remark-frontmatter-5.0.0" = {
      name = "remark-frontmatter";
      packageName = "remark-frontmatter";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-frontmatter/-/remark-frontmatter-5.0.0.tgz";
        sha512 = "XTFYvNASMe5iPN0719nPrdItC9aU0ssC4v14mH1BCi1u0n1gAocqcujWUrByftZTbLhRtiKRyjYTSIOcr69UVQ==";
      };
    };
    "remark-gfm-4.0.1" = {
      name = "remark-gfm";
      packageName = "remark-gfm";
      version = "4.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-gfm/-/remark-gfm-4.0.1.tgz";
        sha512 = "1quofZ2RQ9EWdeN34S79+KExV1764+wCUGop5CPL1WGdD0ocPpu91lzPGbwWMECpEpd42kJGQwzRfyov9j4yNg==";
      };
    };
    "remark-mdx-3.1.1" = {
      name = "remark-mdx";
      packageName = "remark-mdx";
      version = "3.1.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-mdx/-/remark-mdx-3.1.1.tgz";
        sha512 = "Pjj2IYlUY3+D8x00UJsIOg5BEvfMyeI+2uLPn9VO9Wg4MEtN/VTIq2NEJQfde9PnX15KgtHyl9S0BcTnWrIuWg==";
      };
    };
    "remark-parse-11.0.0" = {
      name = "remark-parse";
      packageName = "remark-parse";
      version = "11.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-parse/-/remark-parse-11.0.0.tgz";
        sha512 = "FCxlKLNGknS5ba/1lmpYijMUzX2esxW5xQqjWxw2eHFfS2MSdaHVINFmhjo+qN1WhZhNimq0dZATN9pH0IDrpA==";
      };
    };
    "remark-stringify-11.0.0" = {
      name = "remark-stringify";
      packageName = "remark-stringify";
      version = "11.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/remark-stringify/-/remark-stringify-11.0.0.tgz";
        sha512 = "1OSmLd3awB/t8qdoEOMazZkNsfVTeY4fTsgzcQFdXNq8ToTN4ZGwrMnlda4K6smTFKD+GRV6O48i6Z4iKgPPpw==";
      };
    };
    "request-light-0.5.8" = {
      name = "request-light";
      packageName = "request-light";
      version = "0.5.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/request-light/-/request-light-0.5.8.tgz";
        sha512 = "3Zjgh+8b5fhRJBQZoy+zbVKpAQGLyka0MPgW3zruTF4dFFJ8Fqcfu9YsAvi/rvdcaTeWG3MkbZv4WKxAn/84Lg==";
      };
    };
    "request-light-0.7.0" = {
      name = "request-light";
      packageName = "request-light";
      version = "0.7.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/request-light/-/request-light-0.7.0.tgz";
        sha512 = "lMbBMrDoxgsyO+yB3sDcrDuX85yYt7sS8BfQd11jtbW/z5ZWgLZRcEGLsLoYw7I0WSUGQBs8CC8ScIxkTX1+6Q==";
      };
    };
    "require-from-string-2.0.2" = {
      name = "require-from-string";
      packageName = "require-from-string";
      version = "2.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/require-from-string/-/require-from-string-2.0.2.tgz";
        sha512 = "Xf0nWe6RseziFMu+Ap9biiUbmplq6S9/p+7w7YXP/JBHhrUDDUhwa+vANyubuqfZWTveU//DYVGsDG7RKL/vEw==";
      };
    };
    "s.color-0.0.15" = {
      name = "s.color";
      packageName = "s.color";
      version = "0.0.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/s.color/-/s.color-0.0.15.tgz";
        sha512 = "AUNrbEUHeKY8XsYr/DYpl+qk5+aM+DChopnWOPEzn8YKzOhv4l2zH6LzZms3tOZP3wwdOyc0RmTciyi46HLIuA==";
      };
    };
    "sass-formatter-0.7.9" = {
      name = "sass-formatter";
      packageName = "sass-formatter";
      version = "0.7.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/sass-formatter/-/sass-formatter-0.7.9.tgz";
        sha512 = "CWZ8XiSim+fJVG0cFLStwDvft1VI7uvXdCNJYXhDvowiv+DsbD1nXLiQ4zrE5UBvj5DWZJ93cwN0NX5PMsr1Pw==";
      };
    };
    "semver-7.5.2" = {
      name = "semver";
      packageName = "semver";
      version = "7.5.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.5.2.tgz";
        sha512 = "SoftuTROv/cRjCze/scjGyiDtcUyxw1rgYQSZY7XTmtR5hX+dm76iDbTH8TkLPHCQmlbQVSSbNZCPM2hb0knnQ==";
      };
    };
    "semver-7.7.3" = {
      name = "semver";
      packageName = "semver";
      version = "7.7.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/semver/-/semver-7.7.3.tgz";
        sha512 = "SdsKMrI9TdgjdweUSR9MweHA4EJ8YxHn8DFaDisvhVlUOe4BF1tLD7GAj0lIqWVl+dPb/rExr0Btby5loQm20Q==";
      };
    };
    "stringify-entities-4.0.4" = {
      name = "stringify-entities";
      packageName = "stringify-entities";
      version = "4.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/stringify-entities/-/stringify-entities-4.0.4.tgz";
        sha512 = "IwfBptatlO+QCJUo19AqvrPNqlVMpW9YEL2LIVY+Rpv2qsjCGxaDLNRgeGsQWJhfItebuJhsGSLjaBbNSQ+ieg==";
      };
    };
    "suf-log-2.5.3" = {
      name = "suf-log";
      packageName = "suf-log";
      version = "2.5.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/suf-log/-/suf-log-2.5.3.tgz";
        sha512 = "KvC8OPjzdNOe+xQ4XWJV2whQA0aM1kGVczMQ8+dStAO6KfEB140JEVQ9dE76ONZ0/Ylf67ni4tILPJB41U0eow==";
      };
    };
    "tinyglobby-0.2.15" = {
      name = "tinyglobby";
      packageName = "tinyglobby";
      version = "0.2.15";
      src = fetchurl {
        url = "https://registry.npmjs.org/tinyglobby/-/tinyglobby-0.2.15.tgz";
        sha512 = "j2Zq4NyQYG5XMST4cbs02Ak8iJUdxRM0XI5QyxXuZOzKOINmWurp3smXu3y5wDcJrptwpSjgXHzIQxR0omXljQ==";
      };
    };
    "trough-2.2.0" = {
      name = "trough";
      packageName = "trough";
      version = "2.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/trough/-/trough-2.2.0.tgz";
        sha512 = "tmMpK00BjZiUyVyvrBK7knerNgmgvcV/KLVyuma/SC+TQN167GrMRciANTz09+k3zW8L8t60jWO1GpfkZdjTaw==";
      };
    };
    "typesafe-path-0.2.2" = {
      name = "typesafe-path";
      packageName = "typesafe-path";
      version = "0.2.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/typesafe-path/-/typesafe-path-0.2.2.tgz";
        sha512 = "OJabfkAg1WLZSqJAJ0Z6Sdt3utnbzr/jh+NAHoyWHJe8CMSy79Gm085094M9nvTPy22KzTVn5Zq5mbapCI/hPA==";
      };
    };
    "typescript-4.9.5" = {
      name = "typescript";
      packageName = "typescript";
      version = "4.9.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-4.9.5.tgz";
        sha512 = "1FXk9E2Hm+QzZQ7z+McJiHL4NW1F2EzMu9Nq9i3zAaGqibafqYwCVU6WyWAuyQRRzOlxou8xZSyXLEN8oKj24g==";
      };
    };
    "typescript-5.9.3" = {
      name = "typescript";
      packageName = "typescript";
      version = "5.9.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript/-/typescript-5.9.3.tgz";
        sha512 = "jl1vZzPDinLr9eUt3J/t7V6FgNEw9QjvBPdysz9KfQDD41fQrC2Y4vKQdiaUpFT4bXlb1RHhLpp8wtm6M5TgSw==";
      };
    };
    "typescript-auto-import-cache-0.3.6" = {
      name = "typescript-auto-import-cache";
      packageName = "typescript-auto-import-cache";
      version = "0.3.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/typescript-auto-import-cache/-/typescript-auto-import-cache-0.3.6.tgz";
        sha512 = "RpuHXrknHdVdK7wv/8ug3Fr0WNsNi5l5aB8MYYuXhq2UH5lnEB1htJ1smhtD5VeCsGr2p8mUDtd83LCQDFVgjQ==";
      };
    };
    "uc.micro-2.1.0" = {
      name = "uc.micro";
      packageName = "uc.micro";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/uc.micro/-/uc.micro-2.1.0.tgz";
        sha512 = "ARDJmphmdvUk6Glw7y9DQ2bFkKBHwQHLi2lsaH6PPmz/Ka9sFOBsBluozhDltWmnv9u/cF6Rt87znRTPV+yp/A==";
      };
    };
    "unified-11.0.5" = {
      name = "unified";
      packageName = "unified";
      version = "11.0.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/unified/-/unified-11.0.5.tgz";
        sha512 = "xKvGhPWw3k84Qjh8bI3ZeJjqnyadK+GEFtazSfZv/rKeTkTjOJho6mFqh2SM96iIcZokxiOpg78GazTSg8+KHA==";
      };
    };
    "unist-util-is-6.0.1" = {
      name = "unist-util-is";
      packageName = "unist-util-is";
      version = "6.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-is/-/unist-util-is-6.0.1.tgz";
        sha512 = "LsiILbtBETkDz8I9p1dQ0uyRUWuaQzd/cuEeS1hoRSyW5E5XGmTzlwY1OrNzzakGowI9Dr/I8HVaw4hTtnxy8g==";
      };
    };
    "unist-util-lsp-2.1.0" = {
      name = "unist-util-lsp";
      packageName = "unist-util-lsp";
      version = "2.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-lsp/-/unist-util-lsp-2.1.0.tgz";
        sha512 = "ICI1PWbalSfOrsdosGk+WXdZBvdjhZVjbkgHOzKFdkCdzBpVEi8GjsVTAG6NR3VLGcwTOGLj/+k4L0HwGQYvEQ==";
      };
    };
    "unist-util-position-from-estree-2.0.0" = {
      name = "unist-util-position-from-estree";
      packageName = "unist-util-position-from-estree";
      version = "2.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-position-from-estree/-/unist-util-position-from-estree-2.0.0.tgz";
        sha512 = "KaFVRjoqLyF6YXCbVLNad/eS4+OfPQQn2yOd7zF/h5T/CSL2v8NpN6a5TPvtbXthAGw5nG+PuTtq+DdIZr+cRQ==";
      };
    };
    "unist-util-stringify-position-4.0.0" = {
      name = "unist-util-stringify-position";
      packageName = "unist-util-stringify-position";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-stringify-position/-/unist-util-stringify-position-4.0.0.tgz";
        sha512 = "0ASV06AAoKCDkS2+xw5RXJywruurpbC4JZSm7nr7MOt1ojAzvyyaO+UxZf18j8FCF6kmzCZKcAgN/yu2gm2XgQ==";
      };
    };
    "unist-util-visit-5.0.0" = {
      name = "unist-util-visit";
      packageName = "unist-util-visit";
      version = "5.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-visit/-/unist-util-visit-5.0.0.tgz";
        sha512 = "MR04uvD+07cwl/yhVuVWAtw+3GOR/knlL55Nd/wAdblk27GCVt3lqpTivy/tkJcZoNPzTwS1Y+KMojlLDhoTzg==";
      };
    };
    "unist-util-visit-parents-6.0.2" = {
      name = "unist-util-visit-parents";
      packageName = "unist-util-visit-parents";
      version = "6.0.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/unist-util-visit-parents/-/unist-util-visit-parents-6.0.2.tgz";
        sha512 = "goh1s1TBrqSqukSc8wrjwWhL0hiJxgA8m4kFxGlQ+8FYQ3C/m11FcTs4YYem7V664AhHVvgoQLk890Ssdsr2IQ==";
      };
    };
    "vfile-6.0.3" = {
      name = "vfile";
      packageName = "vfile";
      version = "6.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile/-/vfile-6.0.3.tgz";
        sha512 = "KzIbH/9tXat2u30jf+smMwFCsno4wHVdNmzFyL+T/L3UGqqk6JKfVqOFOZEpZSHADH1k40ab6NUIXZq422ov3Q==";
      };
    };
    "vfile-message-4.0.3" = {
      name = "vfile-message";
      packageName = "vfile-message";
      version = "4.0.3";
      src = fetchurl {
        url = "https://registry.npmjs.org/vfile-message/-/vfile-message-4.0.3.tgz";
        sha512 = "QTHzsGd1EhbZs4AsQ20JX1rC3cOlt/IWJruk893DfLRr57lcnOeMaWG4K0JrRta4mIJZKth2Au3mM3u03/JWKw==";
      };
    };
    "volar-service-css-0.0.68" = {
      name = "volar-service-css";
      packageName = "volar-service-css";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-css/-/volar-service-css-0.0.68.tgz";
        sha512 = "lJSMh6f3QzZ1tdLOZOzovLX0xzAadPhx8EKwraDLPxBndLCYfoTvnNuiFFV8FARrpAlW5C0WkH+TstPaCxr00Q==";
      };
    };
    "volar-service-emmet-0.0.68" = {
      name = "volar-service-emmet";
      packageName = "volar-service-emmet";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-emmet/-/volar-service-emmet-0.0.68.tgz";
        sha512 = "nHvixrRQ83EzkQ4G/jFxu9Y4eSsXS/X2cltEPDM+K9qZmIv+Ey1w0tg1+6caSe8TU5Hgw4oSTwNMf/6cQb3LzQ==";
      };
    };
    "volar-service-html-0.0.68" = {
      name = "volar-service-html";
      packageName = "volar-service-html";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-html/-/volar-service-html-0.0.68.tgz";
        sha512 = "fru9gsLJxy33xAltXOh4TEdi312HP80hpuKhpYQD4O5hDnkNPEBdcQkpB+gcX0oK0VxRv1UOzcGQEUzWCVHLfA==";
      };
    };
    "volar-service-markdown-0.0.65" = {
      name = "volar-service-markdown";
      packageName = "volar-service-markdown";
      version = "0.0.65";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-markdown/-/volar-service-markdown-0.0.65.tgz";
        sha512 = "uEcDR7KXoippfc6cEC/Mnd120w1NpM2JwwvsSAiitPUnO8X5m9XdjxfX3GWlmKZUVN6A7TTcVxAmvSlJQKDs1g==";
      };
    };
    "volar-service-prettier-0.0.68" = {
      name = "volar-service-prettier";
      packageName = "volar-service-prettier";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-prettier/-/volar-service-prettier-0.0.68.tgz";
        sha512 = "grUmWHkHlebMOd6V8vXs2eNQUw/bJGJMjekh/EPf/p2ZNTK0Uyz7hoBRngcvGfJHMsSXZH8w/dZTForIW/4ihw==";
      };
    };
    "volar-service-typescript-0.0.65" = {
      name = "volar-service-typescript";
      packageName = "volar-service-typescript";
      version = "0.0.65";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-typescript/-/volar-service-typescript-0.0.65.tgz";
        sha512 = "zPJuLIMs7lkQCvL+Rza8+3/EIoXEIkX8+DL7bNNfPgnbalbvRDhqWLVMJ6Zk3pINjLJafDqyhSbw8srfkUv97w==";
      };
    };
    "volar-service-typescript-0.0.68" = {
      name = "volar-service-typescript";
      packageName = "volar-service-typescript";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-typescript/-/volar-service-typescript-0.0.68.tgz";
        sha512 = "z7B/7CnJ0+TWWFp/gh2r5/QwMObHNDiQiv4C9pTBNI2Wxuwymd4bjEORzrJ/hJ5Yd5+OzeYK+nFCKevoGEEeKw==";
      };
    };
    "volar-service-typescript-twoslash-queries-0.0.68" = {
      name = "volar-service-typescript-twoslash-queries";
      packageName = "volar-service-typescript-twoslash-queries";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-typescript-twoslash-queries/-/volar-service-typescript-twoslash-queries-0.0.68.tgz";
        sha512 = "NugzXcM0iwuZFLCJg47vI93su5YhTIweQuLmZxvz5ZPTaman16JCvmDZexx2rd5T/75SNuvvZmrTOTNYUsfe5w==";
      };
    };
    "volar-service-yaml-0.0.68" = {
      name = "volar-service-yaml";
      packageName = "volar-service-yaml";
      version = "0.0.68";
      src = fetchurl {
        url = "https://registry.npmjs.org/volar-service-yaml/-/volar-service-yaml-0.0.68.tgz";
        sha512 = "84XgE02LV0OvTcwfqhcSwVg4of3MLNUWPMArO6Aj8YXqyEVnPu8xTEMY2btKSq37mVAPuaEVASI4e3ptObmqcA==";
      };
    };
    "vscode-css-languageservice-6.3.9" = {
      name = "vscode-css-languageservice";
      packageName = "vscode-css-languageservice";
      version = "6.3.9";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-css-languageservice/-/vscode-css-languageservice-6.3.9.tgz";
        sha512 = "1tLWfp+TDM5ZuVWht3jmaY5y7O6aZmpeXLoHl5bv1QtRsRKt4xYGRMmdJa5Pqx/FTkgRbsna9R+Gn2xE+evVuA==";
      };
    };
    "vscode-html-languageservice-5.6.1" = {
      name = "vscode-html-languageservice";
      packageName = "vscode-html-languageservice";
      version = "5.6.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-html-languageservice/-/vscode-html-languageservice-5.6.1.tgz";
        sha512 = "5Mrqy5CLfFZUgkyhNZLA1Ye5g12Cb/v6VM7SxUzZUaRKWMDz4md+y26PrfRTSU0/eQAl3XpO9m2og+GGtDMuaA==";
      };
    };
    "vscode-json-languageservice-4.1.8" = {
      name = "vscode-json-languageservice";
      packageName = "vscode-json-languageservice";
      version = "4.1.8";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-json-languageservice/-/vscode-json-languageservice-4.1.8.tgz";
        sha512 = "0vSpg6Xd9hfV+eZAaYN63xVVMOTmJ4GgHxXnkLCh+9RsQBkWKIghzLhW2B9ebfG+LQQg8uLtsQ2aUKjTgE+QOg==";
      };
    };
    "vscode-json-languageservice-5.7.1" = {
      name = "vscode-json-languageservice";
      packageName = "vscode-json-languageservice";
      version = "5.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-json-languageservice/-/vscode-json-languageservice-5.7.1.tgz";
        sha512 = "sMK2F8p7St0lJCr/4IfbQRoEUDUZRR7Ud0IiSl8I/JtN+m9Gv+FJlNkSAYns2R7Ebm/PKxqUuWYOfBej/rAdBQ==";
      };
    };
    "vscode-jsonrpc-8.2.0" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.2.0.tgz";
        sha512 = "C+r0eKJUIfiDIfwJhria30+TYWPtuHJXHtI7J0YlOmKAo7ogxP20T0zxB7HZQIFhIyvoBPwWskjxrvAtfjyZfA==";
      };
    };
    "vscode-jsonrpc-8.2.1" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "8.2.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-8.2.1.tgz";
        sha512 = "kdjOSJ2lLIn7r1rtrMbbNCHjyMPfRnowdKjBQ+mGq6NAW5QY2bEZC/khaC5OR8svbbjvLEaIXkOq45e2X9BIbQ==";
      };
    };
    "vscode-jsonrpc-9.0.0-next.11" = {
      name = "vscode-jsonrpc";
      packageName = "vscode-jsonrpc";
      version = "9.0.0-next.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-jsonrpc/-/vscode-jsonrpc-9.0.0-next.11.tgz";
        sha512 = "u6LElQNbSiE9OugEEmrUKwH6+8BpPz2S5MDHvQUqHL//I4Q8GPikKLOUf856UnbLkZdhxaPrExac1lA3XwpIPA==";
      };
    };
    "vscode-languageserver-10.0.0-next.16" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "10.0.0-next.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-10.0.0-next.16.tgz";
        sha512 = "RbsYDOhddv1NtBCAR7+oVxxCmOpQUHhrtgUE0xz6J+BJGSCkfOqBCyLUIwSjKk2rK9llxUj/pR5aL8QCsXrxow==";
      };
    };
    "vscode-languageserver-9.0.1" = {
      name = "vscode-languageserver";
      packageName = "vscode-languageserver";
      version = "9.0.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver/-/vscode-languageserver-9.0.1.tgz";
        sha512 = "woByF3PDpkHFUreUa7Hos7+pUWdeWMXRd26+ZX2A8cFx6v/JPTtd4/uN0/jB6XQHYaOlHbio03NTHCqrgG5n7g==";
      };
    };
    "vscode-languageserver-protocol-3.17.5" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.5.tgz";
        sha512 = "mb1bvRJN8SVznADSGWM9u/b07H7Ecg0I3OgXDuLdn307rl/J3A9YD6/eYOssqhecL27hK1IPZAsaqh00i/Jljg==";
      };
    };
    "vscode-languageserver-protocol-3.17.6-next.16" = {
      name = "vscode-languageserver-protocol";
      packageName = "vscode-languageserver-protocol";
      version = "3.17.6-next.16";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-protocol/-/vscode-languageserver-protocol-3.17.6-next.16.tgz";
        sha512 = "kQTjXEuyxMbdmmZ3U+Lib3oUl12xEKNc73RtWxPSDS3TFtjVwt98Q1CUzfDA9EUpsA24M46Bl6q3sLe9AUOKyw==";
      };
    };
    "vscode-languageserver-textdocument-1.0.12" = {
      name = "vscode-languageserver-textdocument";
      packageName = "vscode-languageserver-textdocument";
      version = "1.0.12";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-textdocument/-/vscode-languageserver-textdocument-1.0.12.tgz";
        sha512 = "cxWNPesCnQCcMPeenjKKsOCKQZ/L6Tv19DTRIGuLWe32lyzWhihGVJ/rcckZXJxfdKCFvRLS3fpBIsV/ZGX4zA==";
      };
    };
    "vscode-languageserver-types-3.17.5" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.5";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.5.tgz";
        sha512 = "Ld1VelNuX9pdF39h2Hgaeb5hEZM2Z3jUrrMgWQAu82jMtZp7p3vJT3BzToKtZI7NgQssZje5o0zryOrhQvzQAg==";
      };
    };
    "vscode-languageserver-types-3.17.6-next.6" = {
      name = "vscode-languageserver-types";
      packageName = "vscode-languageserver-types";
      version = "3.17.6-next.6";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-languageserver-types/-/vscode-languageserver-types-3.17.6-next.6.tgz";
        sha512 = "aiJY5/yW+xzw7KPNlwi3gQtddq/3EIn5z8X8nCgJfaiAij2R1APKePngv+MUdLdYJBVTLu+Qa0ODsT+pHgYguQ==";
      };
    };
    "vscode-markdown-languageservice-0.5.0-alpha.11" = {
      name = "vscode-markdown-languageservice";
      packageName = "vscode-markdown-languageservice";
      version = "0.5.0-alpha.11";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-markdown-languageservice/-/vscode-markdown-languageservice-0.5.0-alpha.11.tgz";
        sha512 = "P1uBMAD5iylgpcweWCU1kQwk8SZngktnljXsZk1vFPorXv1mrEI7BkBpOUU0fhVssKgvFlCNLkI7KmwZLC7pdA==";
      };
    };
    "vscode-nls-5.2.0" = {
      name = "vscode-nls";
      packageName = "vscode-nls";
      version = "5.2.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-nls/-/vscode-nls-5.2.0.tgz";
        sha512 = "RAaHx7B14ZU04EU31pT+rKz2/zSl7xMsfIZuo8pd+KZO6PXtQmpevpq3vxvWNcrGbdmhM/rr5Uw5Mz+NBfhVng==";
      };
    };
    "vscode-uri-3.1.0" = {
      name = "vscode-uri";
      packageName = "vscode-uri";
      version = "3.1.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/vscode-uri/-/vscode-uri-3.1.0.tgz";
        sha512 = "/BpdSx+yCQGnCvecbyXdxHDkuk55/G3xwnC0GqY4gmQ3j+A+g8kzzgB4Nk/SINjqn6+waqw3EgbVF2QKExkRxQ==";
      };
    };
    "yallist-4.0.0" = {
      name = "yallist";
      packageName = "yallist";
      version = "4.0.0";
      src = fetchurl {
        url = "https://registry.npmjs.org/yallist/-/yallist-4.0.0.tgz";
        sha512 = "3wdGidZyq5PB084XLES5TpOSRA3wjXAlIWMhum2kRcv/41Sn2emQ0dycQW4uZXLejwKvg6EsvbdlVL+FYEct7A==";
      };
    };
    "yaml-2.7.1" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.7.1";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.7.1.tgz";
        sha512 = "10ULxpnOCQXxJvBgxsn9ptjq6uviG/htZKk9veJGhlqn3w/DxQ631zFF+nlQXLwmImeS5amR2dl2U8sg6U9jsQ==";
      };
    };
    "yaml-2.8.2" = {
      name = "yaml";
      packageName = "yaml";
      version = "2.8.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml/-/yaml-2.8.2.tgz";
        sha512 = "mplynKqc1C2hTVYxd0PU2xQAc22TI1vShAYGksCCfxbn/dFwnHTNi1bvYsBTkhdUNtGIf5xNOg938rrSSYvS9A==";
      };
    };
    "yaml-language-server-1.19.2" = {
      name = "yaml-language-server";
      packageName = "yaml-language-server";
      version = "1.19.2";
      src = fetchurl {
        url = "https://registry.npmjs.org/yaml-language-server/-/yaml-language-server-1.19.2.tgz";
        sha512 = "9F3myNmJzUN/679jycdMxqtydPSDRAarSj3wPiF7pchEPnO9Dg07Oc+gIYLqXR4L+g+FSEVXXv2+mr54StLFOg==";
      };
    };
    "zwitch-2.0.4" = {
      name = "zwitch";
      packageName = "zwitch";
      version = "2.0.4";
      src = fetchurl {
        url = "https://registry.npmjs.org/zwitch/-/zwitch-2.0.4.tgz";
        sha512 = "bXE4cR/kVZhKZX/RjPEflHaKVhUVl85noU3v6b8apfQEc1x4A+zBxjZ4lN8LqGd6WZ3dl98pY4o717VFmoPp+A==";
      };
    };
  };
in
{
  "@astrojs/language-server" = nodeEnv.buildNodePackage {
    name = "_at_astrojs_slash_language-server";
    packageName = "@astrojs/language-server";
    version = "2.16.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/@astrojs/language-server/-/language-server-2.16.3.tgz";
      sha512 = "yO5K7RYCMXUfeDlnU6UnmtnoXzpuQc0yhlaCNZ67k1C/MiwwwvMZz+LGa+H35c49w5QBfvtr4w4Zcf5PcH8uYA==";
    };
    dependencies = [
      sources."@astrojs/compiler-2.13.0"
      sources."@astrojs/yaml2ts-0.2.2"
      sources."@emmetio/abbreviation-2.3.3"
      sources."@emmetio/css-abbreviation-2.1.8"
      sources."@emmetio/css-parser-0.4.1"
      sources."@emmetio/html-matcher-1.3.0"
      sources."@emmetio/scanner-1.0.4"
      sources."@emmetio/stream-reader-2.2.0"
      sources."@emmetio/stream-reader-utils-0.1.0"
      sources."@jridgewell/sourcemap-codec-1.5.5"
      sources."@volar/kit-2.4.27"
      sources."@volar/language-core-2.4.27"
      sources."@volar/language-server-2.4.27"
      sources."@volar/language-service-2.4.27"
      sources."@volar/source-map-2.4.27"
      sources."@volar/typescript-2.4.27"
      sources."@vscode/emmet-helper-2.11.0"
      sources."@vscode/l10n-0.0.18"
      sources."ajv-8.17.1"
      sources."ajv-draft-04-1.0.0"
      sources."emmet-2.4.11"
      sources."fast-deep-equal-3.1.3"
      sources."fast-uri-3.1.0"
      sources."fdir-6.5.0"
      sources."json-schema-traverse-1.0.0"
      sources."jsonc-parser-2.3.1"
      sources."lodash-4.17.21"
      sources."muggle-string-0.4.1"
      sources."path-browserify-1.0.1"
      sources."picomatch-4.0.3"
      sources."prettier-3.8.0"
      sources."prettier-plugin-astro-0.14.1"
      sources."request-light-0.7.0"
      sources."require-from-string-2.0.2"
      sources."s.color-0.0.15"
      sources."sass-formatter-0.7.9"
      sources."semver-7.7.3"
      sources."suf-log-2.5.3"
      sources."tinyglobby-0.2.15"
      sources."typesafe-path-0.2.2"
      sources."typescript-5.9.3"
      sources."typescript-auto-import-cache-0.3.6"
      sources."volar-service-css-0.0.68"
      sources."volar-service-emmet-0.0.68"
      sources."volar-service-html-0.0.68"
      sources."volar-service-prettier-0.0.68"
      sources."volar-service-typescript-0.0.68"
      sources."volar-service-typescript-twoslash-queries-0.0.68"
      sources."volar-service-yaml-0.0.68"
      sources."vscode-css-languageservice-6.3.9"
      sources."vscode-html-languageservice-5.6.1"
      (sources."vscode-json-languageservice-4.1.8" // {
        dependencies = [
          sources."jsonc-parser-3.3.1"
        ];
      })
      sources."vscode-jsonrpc-8.2.0"
      sources."vscode-languageserver-9.0.1"
      sources."vscode-languageserver-protocol-3.17.5"
      sources."vscode-languageserver-textdocument-1.0.12"
      sources."vscode-languageserver-types-3.17.5"
      sources."vscode-nls-5.2.0"
      sources."vscode-uri-3.1.0"
      sources."yaml-2.8.2"
      (sources."yaml-language-server-1.19.2" // {
        dependencies = [
          sources."request-light-0.5.8"
          sources."yaml-2.7.1"
        ];
      })
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "The Astro language server, implement the [language server protocol](https://microsoft.github.io/language-server-protocol/)";
      homepage = "https://github.com/withastro/astro#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@mdx-js/language-server" = nodeEnv.buildNodePackage {
    name = "_at_mdx-js_slash_language-server";
    packageName = "@mdx-js/language-server";
    version = "0.6.3";
    src = fetchurl {
      url = "https://registry.npmjs.org/@mdx-js/language-server/-/language-server-0.6.3.tgz";
      sha512 = "0BvShJa2+EddSinI+mgzoOwtykqwI/HMk5ZlK1XQzxXh2Tfs9wr1tR6/x7Q1ROCKGBP9tZca752agfc94+x01w==";
    };
    dependencies = [
      sources."@mdx-js/language-service-0.7.3"
      sources."@types/debug-4.1.12"
      sources."@types/estree-1.0.8"
      sources."@types/estree-jsx-1.0.5"
      sources."@types/hast-3.0.4"
      sources."@types/mdast-4.0.4"
      sources."@types/ms-2.1.0"
      sources."@types/unist-3.0.3"
      sources."@volar/language-core-2.4.27"
      sources."@volar/language-server-2.4.27"
      sources."@volar/language-service-2.4.27"
      sources."@volar/source-map-2.4.27"
      sources."@volar/typescript-2.4.27"
      sources."@vscode/l10n-0.0.10"
      sources."acorn-8.15.0"
      sources."acorn-jsx-5.3.2"
      sources."argparse-2.0.1"
      sources."bail-2.0.2"
      sources."boolbase-1.0.0"
      sources."ccount-2.0.1"
      sources."character-entities-2.0.2"
      sources."character-entities-html4-2.1.0"
      sources."character-entities-legacy-3.0.0"
      sources."character-reference-invalid-2.0.1"
      sources."css-select-5.2.2"
      sources."css-what-6.2.2"
      sources."debug-4.4.3"
      sources."decode-named-character-reference-1.2.0"
      sources."dequal-2.0.3"
      sources."devlop-1.1.0"
      sources."dom-serializer-2.0.0"
      sources."domelementtype-2.3.0"
      sources."domhandler-5.0.3"
      sources."domutils-3.2.2"
      sources."entities-4.5.0"
      sources."escape-string-regexp-5.0.0"
      sources."estree-util-is-identifier-name-3.0.0"
      sources."estree-util-scope-1.0.0"
      sources."estree-util-visit-2.0.0"
      sources."estree-walker-3.0.3"
      sources."extend-3.0.2"
      sources."fault-2.0.1"
      sources."format-0.2.2"
      sources."he-1.2.0"
      sources."is-alphabetical-2.0.1"
      sources."is-alphanumerical-2.0.1"
      sources."is-decimal-2.0.1"
      sources."is-hexadecimal-2.0.1"
      sources."is-plain-obj-4.1.0"
      sources."linkify-it-5.0.0"
      sources."longest-streak-3.1.0"
      sources."markdown-it-14.1.0"
      sources."markdown-table-3.0.4"
      sources."mdast-util-find-and-replace-3.0.2"
      sources."mdast-util-from-markdown-2.0.2"
      sources."mdast-util-frontmatter-2.0.1"
      sources."mdast-util-gfm-3.1.0"
      sources."mdast-util-gfm-autolink-literal-2.0.1"
      sources."mdast-util-gfm-footnote-2.1.0"
      sources."mdast-util-gfm-strikethrough-2.0.0"
      sources."mdast-util-gfm-table-2.0.0"
      sources."mdast-util-gfm-task-list-item-2.0.0"
      sources."mdast-util-mdx-3.0.0"
      sources."mdast-util-mdx-expression-2.0.1"
      sources."mdast-util-mdx-jsx-3.2.0"
      sources."mdast-util-mdxjs-esm-2.0.1"
      sources."mdast-util-phrasing-4.1.0"
      sources."mdast-util-to-markdown-2.1.2"
      sources."mdast-util-to-string-4.0.0"
      sources."mdurl-2.0.0"
      sources."micromark-4.0.2"
      sources."micromark-core-commonmark-2.0.3"
      sources."micromark-extension-frontmatter-2.0.0"
      sources."micromark-extension-gfm-3.0.0"
      sources."micromark-extension-gfm-autolink-literal-2.1.0"
      sources."micromark-extension-gfm-footnote-2.1.0"
      sources."micromark-extension-gfm-strikethrough-2.1.0"
      sources."micromark-extension-gfm-table-2.1.1"
      sources."micromark-extension-gfm-tagfilter-2.0.0"
      sources."micromark-extension-gfm-task-list-item-2.1.0"
      sources."micromark-extension-mdx-expression-3.0.1"
      sources."micromark-extension-mdx-jsx-3.0.2"
      sources."micromark-extension-mdx-md-2.0.0"
      sources."micromark-extension-mdxjs-3.0.0"
      sources."micromark-extension-mdxjs-esm-3.0.0"
      sources."micromark-factory-destination-2.0.1"
      sources."micromark-factory-label-2.0.1"
      sources."micromark-factory-mdx-expression-2.0.3"
      sources."micromark-factory-space-2.0.1"
      sources."micromark-factory-title-2.0.1"
      sources."micromark-factory-whitespace-2.0.1"
      sources."micromark-util-character-2.1.1"
      sources."micromark-util-chunked-2.0.1"
      sources."micromark-util-classify-character-2.0.1"
      sources."micromark-util-combine-extensions-2.0.1"
      sources."micromark-util-decode-numeric-character-reference-2.0.2"
      sources."micromark-util-decode-string-2.0.1"
      sources."micromark-util-encode-2.0.1"
      sources."micromark-util-events-to-acorn-2.0.3"
      sources."micromark-util-html-tag-name-2.0.1"
      sources."micromark-util-normalize-identifier-2.0.1"
      sources."micromark-util-resolve-all-2.0.1"
      sources."micromark-util-sanitize-uri-2.0.1"
      sources."micromark-util-subtokenize-2.1.0"
      sources."micromark-util-symbol-2.0.1"
      sources."micromark-util-types-2.0.2"
      sources."ms-2.1.3"
      sources."node-html-parser-6.1.13"
      sources."nth-check-2.1.1"
      (sources."parse-entities-4.0.2" // {
        dependencies = [
          sources."@types/unist-2.0.11"
        ];
      })
      sources."path-browserify-1.0.1"
      sources."picomatch-2.3.1"
      sources."punycode.js-2.3.1"
      sources."remark-frontmatter-5.0.0"
      sources."remark-gfm-4.0.1"
      sources."remark-mdx-3.1.1"
      sources."remark-parse-11.0.0"
      sources."remark-stringify-11.0.0"
      sources."request-light-0.7.0"
      sources."semver-7.7.3"
      sources."stringify-entities-4.0.4"
      sources."trough-2.2.0"
      sources."typescript-auto-import-cache-0.3.6"
      sources."uc.micro-2.1.0"
      sources."unified-11.0.5"
      sources."unist-util-is-6.0.1"
      sources."unist-util-lsp-2.1.0"
      sources."unist-util-position-from-estree-2.0.0"
      sources."unist-util-stringify-position-4.0.0"
      sources."unist-util-visit-5.0.0"
      sources."unist-util-visit-parents-6.0.2"
      sources."vfile-6.0.3"
      sources."vfile-message-4.0.3"
      (sources."volar-service-markdown-0.0.65" // {
        dependencies = [
          sources."vscode-jsonrpc-8.2.1"
        ];
      })
      sources."volar-service-typescript-0.0.65"
      sources."vscode-jsonrpc-8.2.0"
      sources."vscode-languageserver-9.0.1"
      sources."vscode-languageserver-protocol-3.17.5"
      sources."vscode-languageserver-textdocument-1.0.12"
      sources."vscode-languageserver-types-3.17.5"
      sources."vscode-markdown-languageservice-0.5.0-alpha.11"
      sources."vscode-nls-5.2.0"
      sources."vscode-uri-3.1.0"
      sources."zwitch-2.0.4"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "A language server for MDX";
      homepage = "https://mdxjs.com";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@tailwindcss/language-server" = nodeEnv.buildNodePackage {
    name = "_at_tailwindcss_slash_language-server";
    packageName = "@tailwindcss/language-server";
    version = "0.14.29";
    src = fetchurl {
      url = "https://registry.npmjs.org/@tailwindcss/language-server/-/language-server-0.14.29.tgz";
      sha512 = "aZ3/XyTNmsoIyhs09Fghlw6D6y7o70aIxHmQEYPFiJPe/1k3HqtxXqhn7g7a5UpA1yeGOyKK9HRNJ8ghZqIclg==";
    };
    buildInputs = globalBuildInputs;
    meta = {
      description = "Tailwind CSS Language Server";
      homepage = "https://github.com/tailwindlabs/tailwindcss-intellisense/tree/HEAD/packages/tailwindcss-language-server#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  "@vtsls/language-server" = nodeEnv.buildNodePackage {
    name = "_at_vtsls_slash_language-server";
    packageName = "@vtsls/language-server";
    version = "0.3.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/@vtsls/language-server/-/language-server-0.3.0.tgz";
      sha512 = "EYTkCHNGz3MFSP7z0DZ5+WBQY5CWEH7bCUu53EaDloBTjghoi2vfZqSrS0+7WsRG03MhBhjGG9ifNee/2kixvQ==";
    };
    dependencies = [
      sources."@vscode/l10n-0.0.18"
      sources."@vtsls/language-service-0.3.0"
      sources."@vtsls/vscode-fuzzy-0.1.0"
      sources."jsonc-parser-3.3.1"
      sources."lru-cache-6.0.0"
      sources."semver-7.5.2"
      sources."typescript-5.9.3"
      sources."vscode-jsonrpc-8.2.0"
      sources."vscode-languageserver-9.0.1"
      sources."vscode-languageserver-protocol-3.17.5"
      sources."vscode-languageserver-textdocument-1.0.12"
      sources."vscode-languageserver-types-3.17.5"
      sources."vscode-uri-3.1.0"
      sources."yallist-4.0.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "LSP wrapper for typescript extension of vscode";
      homepage = "https://github.com/yioneko/vtsls#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
  vscode-langservers-extracted = nodeEnv.buildNodePackage {
    name = "vscode-langservers-extracted";
    packageName = "vscode-langservers-extracted";
    version = "4.10.0";
    src = fetchurl {
      url = "https://registry.npmjs.org/vscode-langservers-extracted/-/vscode-langservers-extracted-4.10.0.tgz";
      sha512 = "EFf9uQI4dAKbzMQFjDvVm1xJq1DXAQvBEuEfPGrK/xzfsL5xWTfIuRr90NgfmqwO+IEt6vLZm9EOj6R66xIifg==";
    };
    dependencies = [
      sources."@vscode/l10n-0.0.18"
      sources."boolbase-1.0.0"
      sources."core-js-3.47.0"
      sources."css-select-5.2.2"
      sources."css-what-6.2.2"
      sources."dom-serializer-2.0.0"
      sources."domelementtype-2.3.0"
      sources."domhandler-5.0.3"
      sources."domutils-3.2.2"
      sources."entities-4.5.0"
      sources."he-1.2.0"
      sources."jsonc-parser-3.3.1"
      sources."node-html-parser-6.1.13"
      sources."nth-check-2.1.1"
      sources."picomatch-2.3.1"
      sources."regenerator-runtime-0.13.11"
      sources."request-light-0.7.0"
      sources."semver-7.7.3"
      sources."typescript-4.9.5"
      sources."vscode-css-languageservice-6.3.9"
      sources."vscode-html-languageservice-5.6.1"
      sources."vscode-json-languageservice-5.7.1"
      sources."vscode-jsonrpc-9.0.0-next.11"
      sources."vscode-languageserver-10.0.0-next.16"
      (sources."vscode-languageserver-protocol-3.17.6-next.16" // {
        dependencies = [
          sources."vscode-languageserver-types-3.17.6-next.6"
        ];
      })
      sources."vscode-languageserver-textdocument-1.0.12"
      sources."vscode-languageserver-types-3.17.5"
      (sources."vscode-markdown-languageservice-0.5.0-alpha.11" // {
        dependencies = [
          sources."@vscode/l10n-0.0.10"
          sources."vscode-jsonrpc-8.2.0"
          sources."vscode-languageserver-protocol-3.17.5"
        ];
      })
      sources."vscode-nls-5.2.0"
      sources."vscode-uri-3.1.0"
    ];
    buildInputs = globalBuildInputs;
    meta = {
      description = "HTML/CSS/JSON/ESLint language servers extracted from [vscode](https://github.com/Microsoft/vscode).";
      homepage = "https://github.com/hrsh7th/vscode-langservers-extracted#readme";
      license = "MIT";
    };
    production = true;
    bypassCache = true;
    reconstructLock = true;
  };
}
