name: flake

on:
  pull_request:
  push:
    branches: [master]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

permissions: {}

jobs:
  check-flake:
    name: check-flake
    permissions:
      contents: read
    timeout-minutes: 10
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: DeterminateSystems/flake-checker-action@3164002371bc90729c68af0e24d5aacf20d7c9f6 # v12
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: radoslawgrochowski-dotfiles
      - run: nix flake check --show-trace --all-systems

  build-flake:
    needs: check-flake
    permissions:
      contents: read
    timeout-minutes: 30
    strategy:
      max-parallel: 1
      matrix:
        include:
          - name: radoslawgrochowski-wsl
            os: ubuntu-latest
            output: ".#nixosConfigurations.radoslawgrochowski-wsl.config.system.build.toplevel"
          - name: macaron
            os: macos-latest
            output: ".#darwinConfigurations.macaron.config.system.build.toplevel"
    name: ${{ matrix.name }}-build
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7
        with:
          persist-credentials: false
      - uses: DeterminateSystems/nix-installer-action@ef8a148080ab6020fd15196c2084a2eea5ff2d25 # v22
      - uses: cachix/cachix-action@5f2d7c5294214f71b873db4b969586b980625e71 # v17
        with:
          authToken: ${{ secrets.CACHIX_AUTH_TOKEN }}
          name: radoslawgrochowski-dotfiles
      - env:
          NIX_BUILD_OUTPUT: ${{ matrix.output }}
        run: nix build "$NIX_BUILD_OUTPUT" -L --show-trace --accept-flake-config
